---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 29.12.18 23:48
---

local RPD = require "scripts/lib/commonClasses"

local trap = require"scripts/lib/trap"

return trap.init(
        function (cell, char, data)
            local hero = RPD.Dungeon.hero

            local pos = RPD.getXy(hero)

            RPD.Dungeon.hero:handle(RPD.Dungeon.level:cell(pos[1],pos[2]-3))
        end
)
