---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/16/20 9:36 PM
---

local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 1,
            imageFile = "items/placeholders.png",
            name      = "ArmorTemplate_Name",
            info      = "ArmorTemplate_Info",
            price     = 17,
            equipable = RPD.Slots.armor
        }
    end,

    getVisualName = function()
        return "ClothArmor"
    end,

    typicalSTR        = function(self, item)
        return 8
    end,

    requiredSTR       = function(self, item)
        return 8
    end,

    effectiveDr        = function(self, item)
        return item:level()
    end,

    defenceProc        = function(self, item, attacker, defender, damage)
        defender:getSprite():showStatus(0x00b77070,"ouch!")
        return damage
    end,
}
