---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 9,
            imageFile = "items/swords.png",
            name      = "BoneSaw_Name",
            info      = "BoneSaw_Info",
            price     = 20,
            equipable = RPD.Slots.weapon
        }
    end,

    goodForMelee = function()
        return true
    end,

    getVisualName = function()
        return "BoneSaw"
    end,

    getAttackAnimationClass = function()
        return "sword"  --look at KindOfWeapon.java for possible values
    end,

    slot = item.slot_bothHands,

    accuracyFactor    = function(self, item, user)
        return 1
    end,

    damageRoll        = function(self, item, user)
        local lvl = item:level()
        return math.random(lvl, lvl*2)
    end,

    attackDelayFactor = function(self, item, user)
        return 1
    end,

    attackProc        = function(self, item, attacker, defender, damage)
        RPD.affectBuff(defender,"Bleeding",3)
        return damage
    end,

    typicalSTR = function(self, item)
        return 9
    end,

    statsRequirementsSatisfied = function(self, item)
        return item:getOwner():effectiveSTR() > 9
    end,

    knownStatsText = function(self, item)
        return ":9"
    end,

    unknownStatsText = function(self, item)
        return "???"
    end
}
