---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 9,
            imageFile = "items/swords.png",
            name      = "BoneSaw_Name",
            info      = "BoneSaw_Info",
            price     = 20,
            equipable = RPD.Slots.weapon
        }
    end,

    goodForMelee = function()
        return true
    end,

    getVisualName = function()
        return "BoneSaw"
    end,

    getAttackAnimationClass = function()
        return "sword"  --look at KindOfWeapon.java for possible values
    end,

    slot = item.slot_bothHands,

    accuracyFactor    = function(self, item, user)
        return 1
    end,

    damageRoll        = function(self, item, user)
        local lvl = item:level()
        return math.random(lvl, lvl*2)
    end,

    attackDelayFactor = function(self, item, user)
        return 1
    end,

    attackProc        = function(self, item, attacker, defender, damage)
        RPD.affectBuff(defender,"Bleeding",3)

        -- Log attack details
        RPD.glog("BoneSaw attack: Attacker=" .. attacker:getEntityKind() .. ", Defender=" .. defender:getEntityKind() .. ", Base Damage=" .. damage)

        -- Check if attacker is a Doctor and if this is a critical hit
        local isDoctor = attacker:getHeroClass():getEntityKind() == "DOCTOR"

        -- Calculate attack and defense skills to determine if it's a critical hit
        local attackSkill = attacker:attackSkill(defender)
        local defenseSkill = defender:defenseSkill(attacker)

        -- Generate random rolls similar to Java implementation
        local acuRoll = math.random() * attackSkill
        local defRoll = math.random() * defenseSkill

        -- A critical hit occurs when the attack roll significantly exceeds the defense roll
        local isCriticalHit = acuRoll > defRoll * 2

        -- Log critical hit calculation
        RPD.glog("BoneSaw critical hit check: AttackSkill=" .. attackSkill .. ", DefenseSkill=" .. defenseSkill ..
                     ", AcuRoll=" .. acuRoll .. ", DefRoll=" .. defRoll .. ", IsCritical=" .. tostring(isCriticalHit))

        -- Apply critical hit bonus if applicable
        local finalDamage = damage
        if isCriticalHit then
            finalDamage = damage * 1.5  -- 50% damage bonus for critical hits
            RPD.glog("BoneSaw critical hit! Damage increased from " .. damage .. " to " .. finalDamage)
        end

        -- Handle critical hit effects for Doctor class - drop extra parts
        if isCriticalHit and isDoctor then
            -- Create random harvestable items to drop
            local harvestItems = {"ToxicGland", "RottenOrgan", "BoneShard", "VileEssence"}
            local randomItem = harvestItems[math.random(1, #harvestItems)]

            local itemToDrop = RPD.ItemFactory:itemByName(randomItem)
            if itemToDrop then
                RPD.Dungeon.level:drop(itemToDrop, defender:getPos())
                RPD.glog("BoneSaw dropped extra part: " .. randomItem .. " at position " .. defender:getPos())
            else
                RPD.glog("BoneSaw failed to create harvest item: " .. randomItem)
            end
        end

        -- Apply 50% damage bonus against paralyzed foes if attacker is Doctor
        if defender.paralysed and isDoctor then
            finalDamage = finalDamage * 1.5
            RPD.glog("BoneSaw bonus vs paralyzed: Damage increased to " .. finalDamage)
        end

        RPD.glog("BoneSaw final damage: " .. finalDamage)
        return finalDamage
    end,

    typicalSTR = function(self, item)
        return 9
    end,

    statsRequirementsSatisfied = function(self, item)
        return item:getOwner():effectiveSTR() > 9
    end,

    knownStatsText = function(self, item)
        return ":9"
    end,

    unknownStatsText = function(self, item)
        return "???"
    end
}
