---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 17,
            imageFile = "items/ammo.png",
            name      = "Kunai_Name",
            info      = "Kunai_Info",
            price     = 17,
            equipable = RPD.Slots.weapon
        }
    end,

    goodForMelee = function()
        return true
    end,

    getVisualName = function()
        return "Dagger"
    end,

    getAttackAnimationClass = function()
        return "Sword"  --look at KindOfWeapon.java for possible values
    end,

    slot = function(self, item, belongings)
        return RPD.Slots.weapon
    end,

    accuracyFactor    = function(self, item, user)
        return 2
    end,

    damageRoll        = function(self, item, user)
        local lvl = item:level()
        return math.random(lvl, lvl*2)
    end,

    attackDelayFactor = function(self, item, user)
        return 0.5
    end,

    isFliesStraight = function(self, item)
        return true
    end
}
