---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 27,
            imageFile = "items/artifacts.png",
            name      = "PlagueDoctorMask_Name",
            info      = "PlagueDoctorMask_Info",
            price     = 20,
            equipable = RPD.Slots.artifact
        }
    end
}
