---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Plague Doctor Harvesting System
--- DateTime: Implementation for Plague Doctor alchemy system
---

local RPD = require "scripts/lib/commonClasses"

local itemLib = require "scripts/lib/item"

return itemLib.init{
    desc  = function ()
        return {
            image     = 81+16,
            imageFile = "items.png",
            name      = "VileEssence_Name",
            info      = "VileEssence_Info",
            price     = 10,
            stackable = true
        }
    end,
    glowing = function(self, item)
        return itemLib.makeGlowing(0xFF550055, 2)
    end,
}