---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/8/23 2:46 AM
---

local RPD = require "scripts/lib/commonClasses"

--RPD.ModQuirks.mobLeveling = true
--RPD.ModQuirks.only2dTiles = false
--RPD.ModQuirks.only3dTiles = false
--RPD.ModQuirks.defaultCarcassChance = 0
--RPD.ModQuirks.noMovingArcs = false
--RPD.ModQuirks.moveTimeout = 0