---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 5:56 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

local speckAdded = false

return mob.init({
    interact = function(self, chr)
        self:say("BardSong_1")
    end,
    act = function(self)
        if not speckAdded then
            local factory = RPD.speckEffectFactory(RPD.Sfx.Speck.NOTE, RPD.Sfx.Speck.UP)
            RPD.pourSpeck(self:getSprite():emitter(), factory, 10)
            speckAdded = true
        end
    end,
})
