---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 5:56 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"


return mob.init({
    interact = function(self, chr)
        self:say("La-la-lA")
    end,
    act = function(self)
        local factory = RPD.speckEffectFactory(RPD.Sfx.Speck.NOTE, RPD.Sfx.Speck.UP)
        RPD.pourSpeck(self:getSprite():emitter(), factory, 10)
    end

})
