---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 11:19 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

local phrases = {
    "Drunkard_Phrase_1",
    "Drunkard_Phrase_2",
    "Drunkard_Phrase_3",
    "Drunkard_Phrase_4"
}

return mob.init({
    interact = function(self, chr)
        self:say(phrases[math.random(1,#phrases)])
    end,

    act = function(self)
        self:setState("Sleeping")
    end
})
