---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 11:32 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

local phrases = {
    "InnServant_Phrase_1",
    "InnServant_Phrase_2",
    "InnServant_Phrase_3",
    "InnServant_Phrase_4"
}

return mob.init({
    interact = function(self, chr)
        self:say(phrases[math.random(1,#phrases)])
    end,

    act = function(self)

        self:setState("MoveOrder")

        local level = RPD.Dungeon.level
        local myTarget = self:getTarget()

        if  level:distance(myTarget,self:getPos()) < 2 or not level:cellValid(myTarget) then
            local targetChar = RPD.Actor:getRandomChar()
            if targetChar:getEntityKind() == self:getEntityKind() then
                return
            end

            self:setTarget(targetChar:getPos())
        end
    end
})
