---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 11:32 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

return mob.init({
    interact = function(self, chr)
        self:say("Hello, ready to order something?")
    end,

    act = function(self)
        if RPD.Dungeon.level:distance(self:getTarget(),self:getPos()) < 2 then
            local targetChar = RPD.Actor:getRandomChar()
            if targetChar == self then
                self:say("Let rest a bit")
                return
            end
            self:say("Going to "..targetChar:getEntityKind())
            self:setTarget(targetChar:getPos())
        end
    end,

})
