---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/17/21 11:32 PM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

local target

return mob.init({
    interact = function(self, chr)
        self:say("Hello, ready to order something?")
    end,

    act = function(self)
        if not target or RPD.Dungeon.level:distance(target,self:getPos()) < 2 then
            target = RPD.Actor:getRandomChar():getPos()
            self:getCloser(target)
        end
    end,

})
