---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 12/23/20 10:01 PM
---

local RPD = require "scripts.lib.commonClasses"
local lru = require "scripts.lib.lru"

local EXPLORATION_CACHE_SIZE = 10
local explorationCache = lru.new(EXPLORATION_CACHE_SIZE);

-- Per-level coverage tracking (#5). Keys are kind strings; presence == "exercised".
-- Cleared on level change by onLeaveLevel, which also dumps the contents.
local function freshCoverage()
    return { items = {}, spells = {}, mobs = {}, windows = {}, buffs = {} }
end
local coverage = freshCoverage()

-- Best-effort buff scan: Char:buffs() returns a java.util.Set (not indexable), so we
-- iterate via its iterator. If the API ever misbehaves, the first failure sticks and
-- disables further scans instead of spamming the log every step.
local buffScanDisabled = false

local ai = {}

-- Curated item types to spawn into the hero's backpack so item code paths get exercised
-- even when the hero doesn't find heaps. Covers consumables, equipment, and utility items.
local testItemPool = {
    "PotionOfHealing", "PotionOfStrength", "PotionOfMana", "PotionOfInvisibility",
    "PotionOfLevitation", "PotionOfMindVision", "PotionOfFrost", "PotionOfPurity",
    "PotionOfToxicGas", "PotionOfParalyticGas",
    "ScrollOfIdentify", "ScrollOfUpgrade", "ScrollOfMagicMapping", "ScrollOfRemoveCurse",
    "ScrollOfTeleportation", "ScrollOfChallenge", "ScrollOfMirrorImage", "ScrollOfRecharging",
    "Dagger", "ShortSword", "Sword", "Mace", "Longsword", "Quarterstaff",
    "ClothArmor", "LeatherArmor", "MailArmor", "ScaleArmor",
    "RingOfAccuracy", "RingOfEvasion", "RingOfHaste", "RingOfMending", "RingOfPower",
    "Ration", "Pasty", "ChargrilledMeat", "MysteryMeat",
    "Sungrass.Seed", "Firebloom.Seed", "Icecap.Seed", "Earthroot.Seed", "Dreamweed.Seed",
    "WandOfMagicMissile", "WandOfFirebolt", "WandOfLightning", "WandOfBlink",
    "Torch", "Ankh", "DewVial", "LloydsBeacon", "ArmorKit",
}

-- #3: runs fn, logs and swallows any error so a single bad decision can't stall the AI.
local function guarded(label, fn)
    local ok, err = pcall(fn)
    if not ok then
        RPD.debug("[autoTestAi] %s error: %s", label, tostring(err))
    end
    return ok
end

-- Safely extract a kind label from a Java object; nil if getEntityKind is unavailable/throws.
local function kindOf(obj)
    if obj == nil then return nil end
    local ok, k = pcall(function() return obj:getEntityKind() end)
    if ok and k ~= nil then return tostring(k) end
    return nil
end

local function track(setName, key)
    if key == nil then return end
    coverage[setName][key] = true
end

local function scanBuffs(hero)
    if buffScanDisabled then return end
    local ok, err = pcall(function()
        local buffs = hero:buffs()
        if not buffs then return end
        local it = buffs:iterator()
        while it:hasNext() do
            local k = kindOf(it:next())
            if k then coverage.buffs[k] = true end
        end
    end)
    if not ok then
        buffScanDisabled = true
        RPD.debug("[autoTestAi] buff scan disabled: %s", tostring(err))
    end
end

local function dumpCoverage(levelLabel)
    local function keys(set)
        local out = {}
        for k in pairs(set) do out[#out + 1] = k end
        table.sort(out)
        if #out == 0 then return "(none)" end
        return table.concat(out, ", ")
    end
    RPD.debug("[autoTestAi] === coverage (%s) ===", levelLabel)
    RPD.debug("[autoTestAi]   items:   %s", keys(coverage.items))
    RPD.debug("[autoTestAi]   spells:  %s", keys(coverage.spells))
    RPD.debug("[autoTestAi]   mobs:    %s", keys(coverage.mobs))
    RPD.debug("[autoTestAi]   windows: %s", keys(coverage.windows))
    RPD.debug("[autoTestAi]   buffs:   %s", keys(coverage.buffs))
end

-- Diagnostic (#5): dump the hero's backpack contents. Uses Belongings:iterator() which
-- walks both equipped and backpack items. Counts "real" items (excludes DummyItem/Gold
-- placeholders) so we can tell at a glance whether item spawning/pickup is working.
local function dumpBackpack(hero)
    local seen = {}
    local realCount = 0
    local total = 0
    local ok, err = pcall(function()
        local iter = hero:getBelongings():iterator()
        while iter:hasNext() do
            local k = kindOf(iter:next())
            if k then
                seen[k] = (seen[k] or 0) + 1
                total = total + 1
                if k ~= "DummyItem" and k ~= "Gold" then
                    realCount = realCount + 1
                end
            end
        end
    end)
    if not ok then
        RPD.debug("[autoTestAi] backpack dump error: %s", tostring(err))
        return
    end
    local parts = {}
    for k, count in pairs(seen) do
        parts[#parts + 1] = string.format("%s x%d", k, count)
    end
    table.sort(parts)
    RPD.debug("[autoTestAi] === backpack ===")
    RPD.debug("[autoTestAi]   real items: %d / %d", realCount, total)
    RPD.debug("[autoTestAi]   contents:  %s", #parts > 0 and table.concat(parts, ", ") or "(empty)")
end

-- Improvement #1: spawn a random item into the hero's backpack. Keeps the backpack stocked
-- with real items to exercise, since the hero rarely picks up dungeon heaps on its own.
-- Caps at 5 real items to avoid filling the backpack.
local function countRealItems(belongings)
    local count = 0
    pcall(function()
        local iter = belongings:iterator()
        while iter:hasNext() do
            local k = kindOf(iter:next())
            if k and k ~= "DummyItem" and k ~= "Gold" then
                count = count + 1
            end
        end
    end)
    return count
end

local function maybeSpawnTestItems(hero)
    if math.random() > 0.02 then return end
    local belongings = hero:getBelongings()
    if belongings:isBackpackFull() then return end
    if countRealItems(belongings) >= 5 then return end

    local itemType = testItemPool[math.random(#testItemPool)]
    guarded("spawnItem:" .. itemType, function()
        hero:collect(RPD.item(itemType))
    end)
end

-- Give items to nearby humanoid mobs so MobItemAi gets exercised.
-- Uses getNearestEnemy to find a target; isHumanoid gates non-humanoid mobs (rats, etc.).
local function maybeGiveItemsToMobs(hero)
    if math.random() > 0.03 then return end
    local enemy = hero:getNearestEnemy()
    if not enemy or not enemy:valid() then return end
    if not enemy:isHumanoid() then return end

    local itemType = testItemPool[math.random(#testItemPool)]
    guarded("giveItemToMob:" .. itemType, function()
        enemy:collect(RPD.item(itemType))
    end)
end

-- Called by scene.lua before changing level (#1 + #5): report what the AI exercised on the
-- level it is leaving, then drop the cell cache (which is keyed by cell number and would
-- otherwise leak into the next level) and reset coverage.
ai.onLeaveLevel = function()
    local levelLabel = "unknown"
    pcall(function() levelLabel = tostring(RPD.Dungeon.hero:level().levelId) end)
    dumpCoverage(levelLabel)
    pcall(function() dumpBackpack(RPD.Dungeon.hero) end)
    explorationCache = lru.new(EXPLORATION_CACHE_SIZE)
    coverage = freshCoverage()
    buffScanDisabled = false
end

local function handleWindow(hero)
    local activeWindow = RPD.RemixedDungeon:scene():getWindow(0)

    if not activeWindow then
        return false
    end

    local wndClass = tostring(activeWindow:getClass())

    if wndClass:match('CellSelector') then
        --RPD.debug("cell selector: %s", wndClass)
        activeWindow = RPD.RemixedDungeon:scene():getWindow(1)
        if not activeWindow then
            return false
        end
        wndClass = tostring(activeWindow:getClass())
    end

    track("windows", wndClass)
    RPD.debug("wnd: %s", wndClass)

    if wndClass:match('WndChar') then
        local target = activeWindow:getTarget()
        local action = RPD.CharUtils:randomAction(target, hero)
        RPD.CharUtils:execute(target, hero, action)
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndStepOnTrap') then
        activeWindow:onSelect(0)
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndItem') then
        activeWindow:onSelect(0)
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndChasmJump') then
        if math.random() < 0.05 then
            activeWindow:onSelect(0)
        else
            activeWindow:onSelect(1)
        end
        return true
    end

    if wndClass:match('Potion') then
        if math.random() < 0.5 then
            activeWindow:onSelect(0)
        else
            activeWindow:onSelect(1)
        end
        activeWindow:hide()
        return true
    end

    if wndClass:match('CellSelectorToast') then
        cell = hero:level():randomDestination()
        RPD.debug("wnd toast: %s %d", wndClass, cell)

        RPD.GameScene:handleCell(cell)
        hero:readyAndIdle()

        return true
    end

    if wndClass:match('WndQuest') then
        activeWindow:hide()
        return true
    end

    if wndClass:match("WndShopOptions") then
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndBag') then
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndStory') then
        activeWindow:hide()
        return true
    end

    if wndClass:match('WndMessage') then
        activeWindow:hide()
        return true
    end

    if wndClass:match('com.watabou.pixeldungeon.scenes.DefaultCellListener') then
        activeWindow:hide()
        return false
    end

    if wndClass:match('CellSelector') then
        RPD.GameScene:handleCell(hero:level():randomDestination())
        return true
    end

    RPD.debug("unmatched wnd: %s", wndClass)

    activeWindow:hide()

    return false

end

local function handleItem(hero, item, ignoreAction)

    if item:getEntityKind() == "Amulet" then
        return
    end

    track("items", kindOf(item))

    local actions = item:actions_l(hero)

    -- Filter out ignoreAction first so we never waste a call picking it and bailing.
    local usable = {}
    for _, a in ipairs(actions) do
        if a ~= ignoreAction then
            usable[#usable + 1] = a
        end
    end

    if #usable > 0 then
        local action = usable[math.random(#usable)]
        guarded("handleItem:" .. tostring(action), function()
            item:execute(hero, action)
        end)
    end
end

ai.step = function()
    local hero = RPD.Dungeon.hero

    if not hero:isReady() then
        return
    end

    scanBuffs(hero)

    maybeSpawnTestItems(hero)

    maybeGiveItemsToMobs(hero)

    local heroPos = hero:getPos()

    -- handleWindow is wrapped as a whole so any window-handler raise is caught and the
    -- AI falls through to normal decision-making this step instead of aborting.
    local hwOk, hwHandled = pcall(function() return handleWindow(hero) end)
    if not hwOk then
        RPD.debug("[autoTestAi] handleWindow error: %s", tostring(hwHandled))
    elseif hwHandled then
        return
    end

    local level = hero:level()

    if hero:buffLevel('Blindness') > 0 then
        local cell = level:getEmptyCellNextTo(heroPos)
        if level:cellValid(cell) then
            guarded("blindStep", function() hero:handle(cell) end)
        else
            hero:rest(false)
        end
        return
    end

    if hero:buffLevel('Charm') == 0 then
        local enemy = hero:getNearestEnemy()
        if enemy and enemy:valid() then
            local enemyPos = enemy:getPos()
            if level:cellValid(enemyPos) and level:adjacent(enemyPos, heroPos) then

                if hero:getSkillPoints() > 0 and math.random() < 0.25 then
                    guarded("castSpell(combat)", function()
                        local spell = RPD.SpellFactory:getRandomSpell()
                        track("spells", kindOf(spell))
                        spell:castOnRandomTarget(hero)
                    end)
                    return
                end

                track("mobs", kindOf(enemy))
                guarded("attackEnemy", function() hero:handle(enemyPos) end)
                return
            end
        end
    end

    if hero:buffLevel('Roots') > 0 or math.random() < 0.025 then
        hero:search(true)
        return
    end

    -- Use a random backpack item (equip/drink/read/eat/identify). Previously this was at
    -- ~5% near the bottom of the priority chain, so it almost never fired while enemies
    -- or heaps competed for attention. Moved up to exercise item code paths more often.
    if not hero:getBelongings():isBackpackEmpty() and math.random() < 0.08 then
        local item = hero:getBelongings():randomUnequipped()
        guarded("useBackpackItem", function() handleItem(hero, item, RPD.Actions.drop) end)
        return
    end

    if not hero:getBelongings():isBackpackFull() then
        local heapPos = level:getNearestVisibleHeapPosition(heroPos)

        if level:cellValid(heapPos) and heapPos ~= heroPos and not explorationCache:get(heapPos) then
            explorationCache:set(heapPos, true)
            guarded("lootHeap", function() hero:handle(heapPos) end)
            return
        end
    end

    if hero:getSkillPoints() > 0 and math.random() < 0.01 then
        guarded("castSpell(idle)", function()
            local spell = RPD.SpellFactory:getRandomSpell()
            track("spells", kindOf(spell))
            spell:castOnRandomTarget(hero)
        end)
        return
    end

    local enemy = hero:getNearestEnemy()
    if enemy and enemy:valid() then
        track("mobs", kindOf(enemy))
        guarded("huntEnemy", function() hero:handle(enemy:getPos()) end)
        return
    end

    local objectPos = level:getNearestVisibleLevelObject(heroPos)

    if level:cellValid(objectPos) then
        local objectKind = level:getTopLevelObject(objectPos):getEntityKind()

        if not explorationCache:get(objectPos) then
            explorationCache:set(objectPos, true)
            guarded("visitObject", function() hero:handle(objectPos) end)
            return
        end

        if objectKind == 'Barrel' and not hero:getBelongings():isBackpackEmpty() and objectPos ~= heroPos then
            guarded("throwAtBarrel", function()
                hero:getBelongings():randomUnequipped():cast(hero, objectPos)
            end)
            return
        end
    end

    -- Drop a random backpack item to free space when getting full.
    if hero:getBelongings():isBackpackFull() and math.random() < 0.25 then
        local item = hero:getBelongings():randomUnequipped()
        guarded("dropItem", function() item:execute(hero, RPD.Actions.drop) end)
        return
    end

    if math.random() < 0.01 then
        local item = hero:getBelongings():randomEquipped()
        track("items", kindOf(item))
        guarded("useEquipped", function() handleItem(hero, item, RPD.Actions.throw) end)
        return
    end

    -- Seek the level exit to descend efficiently rather than relying on the frame timeout.
    do
        local exitCell = level:getRandomVisibleTerrainCell(RPD.Terrain.EXIT)
        if level:cellValid(exitCell) and not level:getTopLevelObject(exitCell) then
            guarded("seekExit", function() hero:handle(exitCell) end)
            return
        end

        exitCell = level:getRandomVisibleTerrainCell(RPD.Terrain.LOCKED_EXIT)
        if level:cellValid(exitCell) and not level:getTopLevelObject(exitCell) and hero:getItem("SkeletonKey"):valid() then
            guarded("seekLockedExit", function() hero:handle(exitCell) end)
            return
        end
    end

    local doorCell = level:getRandomVisibleTerrainCell(RPD.Terrain.DOOR)

    if level:cellValid(doorCell) and not level:isCellVisited(doorCell) then
        guarded("visitDoor", function() hero:handle(doorCell) end)
        return
    end

    doorCell = level:getRandomVisibleTerrainCell(RPD.Terrain.LOCKED_DOOR)

    if level:cellValid(doorCell) and hero:getItem("IronKey"):valid() and not explorationCache:get(doorCell) then
        explorationCache:set(doorCell, true)
        guarded("visitLockedDoor", function() hero:handle(doorCell) end)
        return
    end

    local cell = level:randomTestDestination()
    if not level:cellValid(cell) or cell == heroPos or cell == level:getEntrance() or explorationCache:get(cell) then
        cell = level:randomDestination()
    end

    explorationCache:set(cell, true)

    guarded("explore", function() hero:handle(cell) end)
end

ai.selectCell = function(self)
    RPD.GameScene:handleCell(RPD.Dungeon.level:randomDestination())
end

return ai
