--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 2/20/23 12:36 AM
---

local RPD = require "scripts/lib/commonClasses"
local util = require "scripts/lib/util"
local actor = require "scripts/lib/actor"
local sunfish = require "scripts.stuff.chess.sunfish"

-- caveman: enable bkm_light KRK/KQK solver + opening book (both opt-in).
sunfish.set_use_bkm_light(true)
sunfish.set_book_data(require("scripts.stuff.chess.book"), os.time())

local x0 = 4
local y0 = 4

local pieces = {}
local frozenPets = {}  -- caveman: pets frozen during chess, restored when game ends.

-- caveman: give pets their brain back. if reload (frozenPets lost), un-freeze PASSIVE pets.
local function restorePets()
    if #frozenPets > 0 then
        for _, p in ipairs(frozenPets) do
            if p.mob and p.mob:valid() then
                RPD.setAi(p.mob, p.tag)
            end
        end
    else
        -- caveman: reload case. frozenPets Lua table gone, but Mob AI tag IS stored/restored
        -- by the engine. scan for PASSIVE pets (frozen during chess) and un-freeze to WANDERING.
        local iter = RPD.Dungeon.level.mobs:iterator()
        while iter:hasNext() do
            local mob = iter:next()
            if mob:isPet() and mob:getState():getTag() == "PASSIVE" then
                RPD.setAi(mob, "WANDERING")
            end
        end
    end
    frozenPets = {}
end

pieces_set = {
    ['r'] = 'Eye',
    ['R'] = 'Eye',
    ['n'] = 'Succubus',
    ['N'] = 'Succubus',
    ['b'] = 'Shaman',
    ['B'] = 'Shaman',
    ['Q'] = 'Warlock',
    ['q'] = 'Warlock',
    ['K'] = 'King',
    ['k'] = 'King',
    ['p'] = 'Rat',
    ['P'] = 'Rat'
}

chess = nil

local x_letters = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h' }

local function chessCellFromCell(cell)
    local level = RPD.Dungeon.level

    -- FIX: added local to x and y to prevent global leaks
    local x = level:cellX(cell) - x0
    local y = level:cellY(cell) - y0

    if x >= 0 and x < 8 and y >= 0 and y < 8 then
        local chessCell = x_letters[x + 1] .. tostring(8 - y)
        return chessCell
    end
end

local function cellFromChessCell(chessCell)
    local level = RPD.Dungeon.level

    local x
    for i, letter in ipairs(x_letters) do
        if letter == chessCell:sub(1, 1) then
            x = i - 1
            break
        end
    end
    if not x then
        return nil
    end -- invalid chess cell
    local y = 8 - tonumber(chessCell:sub(2, 2))
    if y < 0 or y > 7 then
        return nil
    end -- invalid chess cell

    return level:cell(x + x0, y + y0)
end

local function cellFromChess(x, y)
    local level = RPD.Dungeon.level
    return level:cell(x + x0, y + y0 - 1)
end

local scheduledMoves = {}

local function movePiece(from, to)
    local fromCell = chessCellFromCell(from)
    local toCell = chessCellFromCell(to)
    if not fromCell or not toCell then
        RPD.glog("movePiece: %s -> %s outside board, skip", tostring(from), tostring(to))
        return
    end

    -- caveman: registry authoritative - never move a stranger found by cell
    local mob = pieces[fromCell]
    if not mob or not mob:valid() then
        RPD.glog("movePiece: no tracked piece on %s -> %s, skip", fromCell, toCell)
        return
    end

    local target = pieces[toCell]
    if target and target ~= mob and target:isAlive() then
        target:die(mob)
    end

    pieces[fromCell] = nil
    pieces[toCell] = mob

    mob:setPos(to)
    mob:moveSprite(from, to)
end

local move_str = ''
local move_cells = {}
local player_chess_cells = {}

local castleMovesList = { 'e1g1', 'e1c1', 'e8g8', 'e8c8' }
local rookMoves = { ['e1g1'] = 'h1f1', ['e1c1'] = 'a1d1',
                    ['e8g8'] = 'h8f8', ['e8c8'] = 'a8d8' }

local enPassantMovesList = { 'a4b3', 'b4a3', 'b4c3', 'c4b3', 'c4d3', 'd4c3', 'd4e3', 'e4d3', 'e4f3', 'f4e3', 'f4g3', 'g4f3', 'g4h3', 'h4g3',
                             'a5b6', 'b5a6', 'b5c6', 'c5b6', 'c5d6', 'd5c6', 'd5e6', 'e5d6', 'e5f6', 'f5e6', 'f5g6', 'g5f6', 'g5h6', 'h5g6' }
local pawnVictim = { ['a4b3'] = 'b4', ['b4a3'] = 'a4', ['b4c3'] = 'c4', ['c4b3'] = 'b4', ['c4d3'] = 'd4', ['d4c3'] = 'c4', ['d4e3'] = 'e4', ['e4d3'] = 'd4', ['e4f3'] = 'f4', ['f4e3'] = 'e4', ['f4g3'] = 'g4', ['g4f3'] = 'f4', ['g4h3'] = 'h4', ['h4g3'] = 'g4',
                     ['a5b6'] = 'b5', ['b5a6'] = 'a5', ['b5c6'] = 'c5', ['c5b6'] = 'b5', ['c5d6'] = 'd5', ['d5c6'] = 'c5', ['d5e6'] = 'e5', ['e5d6'] = 'd5', ['e5f6'] = 'f5', ['f5e6'] = 'e5', ['f5g6'] = 'g5', ['g5f6'] = 'f5', ['g5h6'] = 'h5', ['h5g6'] = 'g5' }

local castleMoves = {}
local enPassantMoves = {}

for _, v in ipairs(castleMovesList) do
    castleMoves[v] = true
end

for _, v in ipairs(enPassantMovesList) do
    enPassantMoves[v] = true
end

local function animateMove(move_str, move_cells, target_chess_cells)

    -- FIX: Verify En Passant by ensuring the target square is EMPTY *before* the move
    local isEnPassant = false
    local epDestCell = chessCellFromCell(move_cells[2])
    if enPassantMoves[move_str] and (epDestCell == nil or pieces[epDestCell] == nil) then
        local epFromCell = chessCellFromCell(move_cells[1])
        local movedMob = epFromCell and pieces[epFromCell]
        if movedMob and movedMob:getEntityKind() == 'Rat' then
            isEnPassant = true
        end
    end

    movePiece(move_cells[1], move_cells[2])

    -- caveman: promotion. pawn (Rat) reach last rank -> swap to promoted piece.
    -- AI move may carry a 5th UCI char (q/r/b/n); player move is 4-char -> queen.
    local destCell = chessCellFromCell(move_cells[2])
    local destMob = destCell and pieces[destCell]
    local destRank = tonumber(string.sub(target_chess_cells[2], 2, 2))
    if destMob and destMob:getEntityKind() == 'Rat' and (destRank == 1 or destRank == 8) then
        destMob:die(destMob)
        local promoChar = string.len(move_str) >= 5 and string.sub(move_str, 5, 5) or 'q'
        local promoted = RPD.MobFactory:mobByName(pieces_set[promoChar] or 'Warlock')
        promoted.noResurrection = true
        promoted.carcassChance = 0
        promoted:setPos(move_cells[2])
        RPD.setAi(promoted, 'PASSIVE')
        RPD.Dungeon.level:spawnMob(promoted)
        promoted:getSprite():tint(destRank == 8 and 0xFF0000 or 0x0000FF, 0.5)
        if destCell then
            pieces[destCell] = promoted
        end
        destMob = promoted
    end

    -- FIX: Castling - Ensure the piece that just moved is actually a King
    if castleMoves[move_str] and destMob and destMob:getEntityKind() == 'King' then
        local rookMove = rookMoves[move_str]
        local cells = { cellFromChessCell(string.sub(rookMove, 1, 2)),
                        cellFromChessCell(string.sub(rookMove, 3, 4)) }
        movePiece(cells[1], cells[2])
    end

    -- caveman: en passant. captured pawn beside destination, remove it.
    if isEnPassant then
        local pawnCell = pawnVictim[move_str]
        local victim = pawnCell and pieces[pawnCell]
        if victim and victim:isAlive() then
            victim:die(victim)
        end
        pieces[pawnCell] = nil
    end
end

local function highlightCells(cells)
    RPD.Sfx.HighlightCell:removeAll()

    for k, cell in pairs(cells) do
        local pos = cellFromChessCell(cell)
        RPD.Sfx.HighlightCell:add(pos)
    end
end

local gameInProgress = true

local function processLose()
    RPD.glog("Chess_YouLose")
    restorePets()
    RPD.Dungeon.hero:die(RPD.Dungeon.hero)
    gameInProgress = false
end

local function processWin()
    restorePets()

    -- caveman: only tracked pieces die - same-kind mobs (real Warlocks on
    -- CityBossLevel) must survive
    local mobsToDie = {}
    for _, mob in pairs(pieces) do
        if mob and mob:isAlive() then
            table.insert(mobsToDie, mob)
        end
    end
    pieces = {}

    for i,mob in ipairs(mobsToDie) do
        mob:die(RPD.Dungeon.hero)
    end

    RPD.glog("Chess_YouWin")

    local level = RPD.Dungeon.level
    local origin = level:getProperty("chessBoardOrigin", "")

    -- caveman: prize chest at board centre (both paths).
    local centerCell = cellFromChessCell("e4")
    local prize = RPD.ItemFactory:itemByName("WandOfFirebolt")
    local heap = level:drop(prize, centerCell)
    heap.type = RPD.Heap.Type.CHEST
    heap.sprite:drop(centerCell)

    if origin and origin ~= "" then
        -- caveman: CityBossLevel. King defeated via chess. Java clears board + badge + unlocks exit.
        level:onChessWin()
    else
        -- caveman: chess_level debug. fill chasm ring + exit portal to town.
        for x = 3, 12 do
            for y = 3, 12 do
                level:set(level:cell(x, y), RPD.Terrain.EMPTY)
            end
        end
        RPD.GameScene:updateMap()

        RPD.createLevelObject(
                {kind = "PortalGateSender", target = {levelId = "town_2", x = 12, y = 28}},
                cellFromChessCell("e2")
        )
    end

    gameInProgress = false
end

-- caveman: stalemate tie. King yields and lets hero pass. becomes neutral (fights back if hurt).
-- clears the other 31 pieces, replaces the Java King piece with a NeutralKing mob.
local function processTie()
    RPD.glog("Chess_Stalemate")
    restorePets()

    local level = RPD.Dungeon.level
    local kingCell = nil
    local toClear = {}

    -- caveman: tracked pieces only, same as processWin
    for _, m in pairs(pieces) do
        if m and m:isAlive() then
            if m:getEntityKind() == "King" and kingCell == nil then
                kingCell = m:getPos() -- caveman: remember where the king stood
            end
            toClear[#toClear + 1] = m
        end
    end
    pieces = {}

    for _, m in ipairs(toClear) do
        if m:getEntityKind() == "King" then
            m:destroy() -- caveman: remove boss piece cleanly (no SkeletonKey / boss-death fx)
        else
            m:die(RPD.Dungeon.hero)
        end
    end

    -- caveman: neutral king takes the old king's place. passive until provoked.
    if kingCell then
        RPD.spawnMob("NeutralKing", kingCell)
    end

    local origin = level:getProperty("chessBoardOrigin", "")
    if origin and origin ~= "" then
        -- caveman: CityBossLevel. clear board (chasm -> floor) + unlock exit. no boss-slain badge.
        level:onChessTie()
    else
        -- caveman: chess_level debug. clear board + portal out (same as win).
        for x = 3, 12 do
            for y = 3, 12 do
                level:set(level:cell(x, y), RPD.Terrain.EMPTY)
            end
        end
        RPD.GameScene:updateMap()
        RPD.createLevelObject(
                {kind = "PortalGateSender", target = {levelId = "town_2", x = 12, y = 28}},
                cellFromChessCell("e2")
        )
    end

    gameInProgress = false
end

local AI_DELAY_MS = 800

local aiCoroutine = nil     -- caveman: background AI search fiber.
local aiResult = nil        -- caveman: result from the coroutine when it finishes.
local kingInCheckCell = nil -- caveman: king cell if in check, nil otherwise.
local checkFlashTimer = 0  -- caveman: flash timer for king-in-check visual.
local aiMoveAt = 0
local allowedMoves = {}
local halfmoveClock = 0 -- caveman: plies since last pawn move / capture (50-move rule; 100 = draw)

local function getPiece(board, engineCell)
    return string.sub(board, engineCell+1, engineCell + 1)
end

-- caveman: 50-move rule. a move resets the clock if it is a pawn move (incl.
-- en passant / promotion) or a capture. `board` is the PRE-move board, standard frame.
local function resetsFifty(board, moveStr)
    local mover = getPiece(board, sunfish.cell_2_move(string.sub(moveStr, 1, 2)))
    if mover == 'P' or mover == 'p' then return true end
    local target = getPiece(board, sunfish.cell_2_move(string.sub(moveStr, 3, 4)))
    return target ~= '.' and target ~= ' ' and target ~= '\n'
end

-- caveman: tick the halfmove clock for `moveStr` on the PRE-move `board`.
-- returns true if the 50-move draw (100 plies) has been reached.
local function tickFifty(board, moveStr)
    if resetsFifty(board, moveStr) then
        halfmoveClock = 0
    else
        halfmoveClock = halfmoveClock + 1
    end
    return halfmoveClock >= 100
end

-- caveman: insufficient material -> draw (tie). KvK, KBK, KNK, and KBKB with
-- bishops on the same color. Any pawn or major (Q/R) means sufficient material.
local function isInsufficientMaterial(board)
    local wMinors, bMinors = 0, 0
    local wBishopColor, bBishopColor
    for c = 1, #board do
        local ch = board:sub(c, c)
        if ch == 'P' or ch == 'p' or ch == 'Q' or ch == 'q' or ch == 'R' or ch == 'r' then
            return false -- pawn or major -> sufficient
        elseif ch == 'N' or ch == 'B' then
            wMinors = wMinors + 1
            if wMinors == 1 and ch == 'B' then
                local col = (c - 1) % 10; wBishopColor = (col + (c - 1 - col) / 10) % 2
            end
        elseif ch == 'n' or ch == 'b' then
            bMinors = bMinors + 1
            if bMinors == 1 and ch == 'b' then
                local col = (c - 1) % 10; bBishopColor = (col + (c - 1 - col) / 10) % 2
            end
        end
    end
    if wMinors == 0 and bMinors == 0 then return true end                       -- KvK
    if wMinors + bMinors == 1 then return true end                               -- KBK / KNK
    if wMinors == 1 and bMinors == 1
       and wBishopColor ~= nil and bBishopColor ~= nil
       and wBishopColor == bBishopColor then return true end                     -- KBKB same color
    return false
end

-- caveman: tint all chess pieces red (player/uppercase) or blue (AI/lowercase).
-- Called every onStep frame so resize (sprite recreate) is recovered within one
-- frame. tint() is idempotent (sets absolute values, doesn't accumulate).
local function retintPieces()
    if not chess then return end
    if #scheduledMoves > 0 then return end -- caveman: skip during animation — board is ahead of visuals
    chess:ensure_board()
    local boardData = util.split(chess.board, "\n")
    for i, v in ipairs(boardData) do
        if i >= 3 and i <= 10 then
            local y = i - 2
            local bcell = cellFromChess(0, y)
            for ii = 1, 8 do
                local piece = string.sub(v, ii + 1, ii + 1)
                if pieces_set[piece] then
                    local cc = chessCellFromCell(bcell)
                    local mob = cc and pieces[cc]
                    if mob and mob:valid() and mob:getSprite() then
                        mob:getSprite():tint(piece == piece:upper() and 0xFF0000 or 0x0000FF, 0.5)
                    end
                end
                bcell = bcell + 1
            end
        end
    end
end

-- caveman: board self-heal. engine board is authoritative: a square that must
-- hold a piece but lost its mob (killed by hero/pet out-of-band) gets a fresh
-- piece. keeps picture == engine (#21), killing pieces can't break the game.
local function repairPieces()
    if not chess then return end
    if #scheduledMoves > 0 then return end
    chess:ensure_board()
    local boardData = util.split(chess.board, "\n")
    for i, v in ipairs(boardData) do
        if i >= 3 and i <= 10 then
            local y = i - 2
            local cell = cellFromChess(0, y)
            for ii = 1, 8 do
                local piece = string.sub(v, ii + 1, ii + 1)
                local cc = chessCellFromCell(cell)
                if pieces_set[piece] and cc then
                    local mob = pieces[cc]
                    if not mob or not mob:valid() or not mob:isAlive() then
                        local fresh = RPD.MobFactory:mobByName(pieces_set[piece])
                        fresh.noResurrection = true
                        fresh.carcassChance = 0
                        fresh:setPos(cell)
                        RPD.setAi(fresh, 'PASSIVE')
                        RPD.Dungeon.level:spawnMob(fresh)
                        fresh:getSprite():tint(piece == piece:upper() and 0xFF0000 or 0x0000FF, 0.5)
                        pieces[cc] = fresh
                        RPD.glog("chess: repaired %s on %s", pieces_set[piece], cc)
                    end
                end
                cell = cell + 1
            end
        end
    end
end

return actor.init({
    act = function()
        return true
    end,

    onStep = function()
        -- caveman: re-tint every frame. tint() is idempotent (sets absolute values),
        -- and resize recreates sprites — so per-frame tinting recovers from resize
        -- within one frame. registry lookups only, negligible cost.
        retintPieces()
        repairPieces()

        -- caveman: resume AI search fiber. yields every 256 nodes (YIELD_QUANTUM). keeps animations alive.
        -- fiber = zero-thread luaj lib: no JVM thread per search, heap frames only.
        if aiCoroutine then
            local ok, err = fiber.resume(aiCoroutine)
            if not ok then
                RPD.glog("AI search error: %s", tostring(err))
                aiCoroutine = nil
            elseif fiber.status(aiCoroutine) == "dead" then
                aiCoroutine = nil
                -- caveman: process AI result. moved here from cellClicked so search runs async.
                local result = aiResult
                aiResult = nil
                local ai_move = result.ai_move
                -- caveman: 50-move rule on the AI's move (pre-move board is chess, standard frame).
                local fiftyDraw = ai_move and tickFifty(chess:ensure_board(), ai_move) or false
                chess = result.chess
                local score = result.score
                local insufficient = isInsufficientMaterial(chess:ensure_board()) -- caveman: KvK/KBK/KNK/KBKB

                -- caveman: outcome from search score. -MATE = AI got mated = player win.
                local match_end = nil
                if score <= -sunfish.MATE_VALUE then match_end = "win" end
                if score >= sunfish.MATE_VALUE then match_end = "lose" end
                if not match_end and (fiftyDraw or insufficient) then match_end = "tie" end -- caveman: draw

                if not ai_move then
                    -- caveman: AI had no move. mated -> win; stalemated -> tie; else lose.
                    if match_end == "win" then
                        processWin()
                    elseif sunfish.is_stalemate(chess) then
                        processTie()
                    else
                        processLose()
                    end
                    return
                end

                -- caveman: AI moved. chess is now player-to-move frame. materialize lazy board.
                chess:ensure_board()

                -- caveman: player mated by AI? score flags mate, not stalemate.
                -- stalemate = tie (King yields). checkmate = lose.
                if not match_end then
                    if sunfish.is_checkmate(chess) then match_end = "lose"
                    elseif sunfish.is_stalemate(chess) then match_end = "tie" end
                end

                -- caveman: player in check after AI move? flash player king cell.
                kingInCheckCell = nil
                if chess:in_check() then
                    local ki = chess:king_index() -- 1-based square of player king (K)
                    if ki then
                        kingInCheckCell = cellFromChessCell(sunfish.move_2_cell(ki - 1))
                    end
                end

                -- caveman: queue AI move for animation. win/lose fires after it visually lands.
                local atc = { string.sub(ai_move, 1, 2), string.sub(ai_move, 3, 4) }
                local ac = { cellFromChessCell(atc[1]), cellFromChessCell(atc[2]) }
                table.insert(scheduledMoves, { ai_move, ac, atc, match_end })
                aiMoveAt = RPD.SystemTime:now()
                RPD.glog("queued AI move %s cells=%s,%s queued=%d match_end=%s", tostring(ai_move), tostring(ac[1]), tostring(ac[2]), #scheduledMoves, tostring(match_end))
            end
            return -- don't process scheduled moves while AI is thinking
        end

        -- caveman: king-in-check visual. flash red particles on the king every ~30 frames.
        if kingInCheckCell then
            checkFlashTimer = checkFlashTimer + 1
            if checkFlashTimer >= 30 then
                checkFlashTimer = 0
                local kingCC = chessCellFromCell(kingInCheckCell)
                local mob = kingCC and pieces[kingCC]
                if mob and mob:getSprite() then
                    mob:getSprite():emitter():burst(RPD.Sfx.ElmoParticle.FACTORY, 3)
                end
            end
        end

        if #scheduledMoves > 0 then
            -- caveman: diagnostic. if this not show in slog, onStep not running.
            local elapsed = RPD.SystemTime:now() - aiMoveAt
            if elapsed >= AI_DELAY_MS then
                RPD.glog("onStep: draining AI move (queued=%d)", #scheduledMoves)
                local m = scheduledMoves[1]
                animateMove(m[1], m[2], m[3])

                -- FIX: Process delayed win/loss so the final move is visible
                local match_end = m[4]
                table.remove(scheduledMoves, 1)

                if match_end == "win" then
                    processWin()
                elseif match_end == "lose" then
                    processLose()
                elseif match_end == "tie" then
                    processTie()
                end
            end
        end
    end,

    actionTime = function()
        return 0.1
    end,

    activate = function(data)
        RPD.Dungeon.hero:interrupt()

        -- caveman: ask Java where board a8 cell is. refresh every activate (level may differ).
        -- default 4,4 = chess_level debug level. CityBossLevel returns the carved hall board.
        local lvl = RPD.Dungeon.level
        -- caveman: ask Java where board a8 cell is (via level property). default 4,4 = chess_level.
        local origin = tonumber(lvl:getProperty("chessBoardOrigin", ""))
        if origin and origin >= 0 then
            x0 = lvl:cellX(origin)
            y0 = lvl:cellY(origin)
        else
            x0 = 4
            y0 = 4
        end

        -- caveman: save/load. "OVER" = game already won/lost. don't restart.
        if data == "OVER" then
            gameInProgress = false
            return
        end

        -- caveman: save/load. use restore_data so piece_count/material/fifty are
        -- initialized from the board (bkm_light gate needs piece_count == 3).
        if data and data ~= "" then
            local parts = util.split(data, "|")
            chess = sunfish.restore_data({
                board = parts[1] or "",
                score = tonumber(parts[2]) or 0,
                wc = { parts[3]:sub(1,1) == "T", parts[3]:sub(2,2) == "T" },
                bc = { parts[4]:sub(1,1) == "T", parts[4]:sub(2,2) == "T" },
                ep = tonumber(parts[5]) or 0,
                kp = tonumber(parts[6]) or 0,
                fifty = tonumber(parts[7]) or 0,
            })
            gameInProgress = true
            move_str = ''
            scheduledMoves = {}
            allowedMoves = {}

            -- caveman: rebuild the piece registry positionally. deterministic at
            -- load time: piece mobs were just deserialized at their saved squares.
            pieces = {}
            chess:ensure_board()
            local boardData = util.split(chess.board, "\n")
            for i, v in ipairs(boardData) do
                if i >= 3 and i <= 10 then
                    local y = i - 2
                    local cell = cellFromChess(0, y)
                    for ii = 1, 8 do
                        local piece = string.sub(v, ii + 1, ii + 1)
                        local cc = chessCellFromCell(cell)
                        if pieces_set[piece] and cc then
                            local mob = RPD.Actor:findChar(cell)
                            if mob then
                                pieces[cc] = mob
                            end
                        end
                        cell = cell + 1
                    end
                end
            end

            -- caveman: retintPieces() runs every onStep frame, no flag needed.

        elseif not chess then
            gameInProgress = true
            move_str = ''
            scheduledMoves = {}
            allowedMoves = {}
            chess = sunfish.new()
            halfmoveClock = 0 -- caveman: fresh game, reset 50-move clock
            pieces = {}

            -- caveman: freeze hero pets so they not walk board / kill pieces / get captured.
            -- save their ai tag now, restore when game ends (processWin / processLose).
            frozenPets = {}
            local mobsIter = RPD.Dungeon.level.mobs:iterator()
            while mobsIter:hasNext() do
                local mob = mobsIter:next()
                if mob:isPet() then
                    frozenPets[#frozenPets + 1] = { mob = mob, tag = mob:getState():getTag() }
                    RPD.setAi(mob, "PASSIVE")
                end
            end

            local level = RPD.Dungeon.level

            local boardData = util.split(chess.board, "\n")
            for i, v in ipairs(boardData) do
                print(v)
                if i >= 3 and i <= 10 then
                    local y = i - 2
                    local cell = cellFromChess(0, y)

                    for ii = 1, 8 do
                        local chessCell = chessCellFromCell(cell)
                        local piece = string.sub(v, ii + 1, ii + 1)

                        if pieces_set[piece] then
                            local mob = RPD.MobFactory:mobByName(pieces_set[piece])

                            -- caveman: pieces must not resurrect/reanimate - breaks the board
                            mob.noResurrection = true
                            mob.carcassChance = 0
                            mob:setPos(cell)
                            RPD.setAi(mob, "PASSIVE")
                            level:spawnMob(mob)

                            if piece == piece:upper() then
                                mob:getSprite():tint(0xFF0000, 0.5)
                            else
                                mob:getSprite():tint(0x0000FF, 0.5)
                            end

                            pieces[chessCell] = mob
                        end
                        cell = cell + 1
                    end
                end
            end
        end
    end,

    cellClicked = function(cell)

        if not gameInProgress then
            RPD.glog("chess: gameInProgress=false, click ignored")
            return false
        end

        -- caveman: AI thinking. block player input so they can't move during AI search.
        if aiCoroutine then
            return true
        end

        RPD.Dungeon.hero:interrupt()

        -- FIX: added local
        local chessCell = chessCellFromCell(cell)

        if not chessCell then
            RPD.glog("Chess_YourMove")
            return true
        end

        RPD.glog("chess click: cell=%d chessCell=%s move_str='%s'", cell, tostring(chessCell), move_str)

        -- FIX: added local
        local engineCell = sunfish.cell_2_move(chessCell)

        RPD.Sfx.HighlightCell:removeAll()

        if string.len(move_str) == 0 then

            -- FIX: Ignore empty cells / enemy piece clicks when starting a selection
            local clickedPiece = getPiece(chess.board, engineCell)
            RPD.glog("chess select: chessCell=%s engineCell=%s piece='%s'", chessCell, tostring(engineCell), clickedPiece)
            if not string.match(clickedPiece, "%u") then
                RPD.glog("chess select: not your piece (lowercase or empty), ignored")
                return true
            end

            move_cells[1] = cell
            player_chess_cells[1] = chessCell
            move_str = chessCell

            allowedMoves = {}

            -- caveman: engine hands legal moves as coord strings ("e2e4"). keep the ones
            -- that start on the clicked square; their destinations are the highlights.
            local hCells = { chessCell }
            for _, uci in ipairs(sunfish.legal_moves_uci(chess)) do
                if string.sub(uci, 1, 2) == chessCell then
                    local to = string.sub(uci, 3, 4)
                    allowedMoves[to] = true
                    table.insert(hCells, to)
                end
            end

            local selectedMob = pieces[chessCell]
            if selectedMob and selectedMob:isAlive() then
                selectedMob:getSprite():emitter():burst(RPD.Sfx.ElmoParticle.FACTORY, 4)
            end

            highlightCells(hCells)
        else

            -- FIX: added local
            local clickedPiece = getPiece(chess.board, engineCell)
            if string.match(clickedPiece,"%u") then
                -- Re-selecting own piece. Reset and require another click.
                move_str = ''
                RPD.Sfx.HighlightCell:removeAll()
                return true
            end

            if not allowedMoves[chessCell] then
                RPD.glog("illegal move: %s", chessCell)
                -- FIX: Don't lock out the player, reset the attempt!
                move_str = ''
                RPD.Sfx.HighlightCell:removeAll()
                return true
            end

            move_str = move_str .. chessCell
            move_cells[2] = cell
            player_chess_cells[2] = chessCell

            local moveResult = sunfish.move(chess, move_str)

            if moveResult then
                local fiftyDraw = tickFifty(chess.board, move_str) -- caveman: 50-move check on pre-move board
                chess = moveResult:rotate()
                chess:ensure_board() -- caveman: rotate() leaves board nil (lazy). materialize it.
                local insufficient = isInsufficientMaterial(chess.board) -- caveman: KvK/KBK/KNK/KBKB

                RPD.Sfx.HighlightCell:removeAll()
                animateMove(move_str, move_cells, player_chess_cells)

                if fiftyDraw or insufficient then
                    processTie() -- caveman: draw (50-move or insufficient material) -> tie
                else
                    -- caveman: launch AI search as fiber. yields every 256 nodes (YIELD_QUANTUM).
                    -- onStep resumes it each frame so game animations keep running during deep search.
                    aiCoroutine = fiber.create(function()
                        local c, m, s = sunfish.ai_move(chess:rotate())
                        aiResult = { chess = c, ai_move = m, score = s }
                    end)
                end
            else
                RPD.glog('illegal move')
            end
            move_str = ''
        end

        return true
    end,

    -- caveman: serialize sunfish state for save/load. ScriptedActor calls this on save.
    serialize = function()
        if not chess or not gameInProgress then return "OVER" end
        chess:ensure_board() -- caveman: board can be nil (lazy) after move/rotate. materialize before concat.
        -- caveman: use | not \n — chess.board itself contains \n (row separators).
        return chess.board .. "|" ..
               tostring(chess.score) .. "|" ..
               (chess.wc[1] and "T" or "F") .. (chess.wc[2] and "T" or "F") .. "|" ..
               (chess.bc[1] and "T" or "F") .. (chess.bc[2] and "T" or "F") .. "|" ..
               tostring(chess.ep) .. "|" ..
               tostring(chess.kp) .. "|" ..
               tostring(halfmoveClock)
    end
})