--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 2/20/23 12:36 AM
---

local RPD = require "scripts/lib/commonClasses"
local util = require "scripts/lib/util"
local actor = require "scripts/lib/actor"
local sunfish = require "scripts.stuff.chess.sunfish"

local x0 = 4
local y0 = 4

local pieces = {}
local frozenPets = {}  -- caveman: pets frozen during chess, restored when game ends.

-- caveman: give pets their brain back. if reload (frozenPets lost), un-freeze PASSIVE pets.
local function restorePets()
    if #frozenPets > 0 then
        for _, p in ipairs(frozenPets) do
            if p.mob and p.mob:valid() then
                RPD.setAi(p.mob, p.tag)
            end
        end
    else
        -- caveman: reload case. frozenPets Lua table gone, but Mob AI tag IS stored/restored
        -- by the engine. scan for PASSIVE pets (frozen during chess) and un-freeze to WANDERING.
        local iter = RPD.Dungeon.level.mobs:iterator()
        while iter:hasNext() do
            local mob = iter:next()
            if mob:isPet() and mob:getState():getTag() == "PASSIVE" then
                RPD.setAi(mob, "WANDERING")
            end
        end
    end
    frozenPets = {}
end

pieces_set = {
    ['r'] = 'Eye',
    ['R'] = 'Eye',
    ['n'] = 'Succubus',
    ['N'] = 'Succubus',
    ['b'] = 'Shaman',
    ['B'] = 'Shaman',
    ['Q'] = 'Warlock',
    ['q'] = 'Warlock',
    ['K'] = 'King',
    ['k'] = 'King',
    ['p'] = 'Rat',
    ['P'] = 'Rat'
}

chess = nil

local x_letters = { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h' }

local function chessCellFromCell(cell)
    local level = RPD.Dungeon.level

    -- FIX: added local to x and y to prevent global leaks
    local x = level:cellX(cell) - x0
    local y = level:cellY(cell) - y0

    if x >= 0 and x < 8 and y >= 0 and y < 8 then
        local chessCell = x_letters[x + 1] .. tostring(8 - y)
        return chessCell
    end
end

local function cellFromChessCell(chessCell)
    local level = RPD.Dungeon.level

    local x
    for i, letter in ipairs(x_letters) do
        if letter == chessCell:sub(1, 1) then
            x = i - 1
            break
        end
    end
    if not x then
        return nil
    end -- invalid chess cell
    local y = 8 - tonumber(chessCell:sub(2, 2))
    if y < 0 or y > 7 then
        return nil
    end -- invalid chess cell

    return level:cell(x + x0, y + y0)
end

local function cellFromChess(x, y)
    local level = RPD.Dungeon.level
    return level:cell(x + x0, y + y0 - 1)
end

local scheduledMoves = {}

local function movePiece(from, to)
    local mob = RPD.Actor:findChar(from)
    if not mob then
        RPD.debug("movePiece: no mob on cell %s -> %s, skip", tostring(from), tostring(to))
        return
    end
    local target = RPD.Actor:findChar(to)

    if not target then
        mob:setPos(to)
        mob:moveSprite(from, to)
        return
    end

    if target then
        target:die(mob)
        mob:setPos(to)
        mob:moveSprite(from, to)
    end
end

local move_str = ''
local move_cells = {}
local player_chess_cells = {}

local castleMovesList = { 'e1g1', 'e1c1', 'e8g8', 'e8c8' }
local rookMoves = { ['e1g1'] = 'h1f1', ['e1c1'] = 'a1d1',
                    ['e8g8'] = 'h8f8', ['e8c8'] = 'a8d8' }

local enPassantMovesList = { 'a4b3', 'b4a3', 'b4c3', 'c4b3', 'c4d3', 'd4c3', 'd4e3', 'e4d3', 'e4f3', 'f4e3', 'f4g3', 'g4f3', 'g4h3', 'h4g3',
                             'a5b6', 'b5a6', 'b5c6', 'c5b6', 'c5d6', 'd5c6', 'd5e6', 'e5d6', 'e5f6', 'f5e6', 'f5g6', 'g5f6', 'g5h6', 'h5g6' }
local pawnVictim = { ['a4b3'] = 'b4', ['b4a3'] = 'a4', ['b4c3'] = 'c4', ['c4b3'] = 'b4', ['c4d3'] = 'd4', ['d4c3'] = 'c4', ['d4e3'] = 'e4', ['e4d3'] = 'd4', ['e4f3'] = 'f4', ['f4e3'] = 'e4', ['f4g3'] = 'g4', ['g4f3'] = 'f4', ['g4h3'] = 'h4', ['h4g3'] = 'g4',
                     ['a5b6'] = 'b5', ['b5a6'] = 'a5', ['b5c6'] = 'c5', ['c5b6'] = 'b5', ['c5d6'] = 'd5', ['d5c6'] = 'c5', ['d5e6'] = 'e5', ['e5d6'] = 'd5', ['e5f6'] = 'f5', ['f5e6'] = 'e5', ['f5g6'] = 'g5', ['g5f6'] = 'f5', ['g5h6'] = 'h5', ['h5g6'] = 'g5' }

local castleMoves = {}
local enPassantMoves = {}

for _, v in ipairs(castleMovesList) do
    castleMoves[v] = true
end

for _, v in ipairs(enPassantMovesList) do
    enPassantMoves[v] = true
end

local function animateMove(move_str, move_cells, target_chess_cells)

    -- FIX: Verify En Passant by ensuring the target cell is EMPTY *before* the move
    local isEnPassant = false
    local targetMob = RPD.Actor:findChar(move_cells[2])
    if enPassantMoves[move_str] and not targetMob then
        local movedMob = RPD.Actor:findChar(move_cells[1])
        if movedMob and movedMob:getEntityKind() == 'Rat' then
            isEnPassant = true
        end
    end

    movePiece(move_cells[1], move_cells[2])

    -- caveman: promotion. pawn (Rat) reach last rank -> swap to Warlock (queen).
    local destRank = tonumber(string.sub(target_chess_cells[2], 2, 2))
    local destMob = RPD.Actor:findChar(move_cells[2])
    if destMob and destMob:getEntityKind() == 'Rat' and (destRank == 1 or destRank == 8) then
        destMob:die(destMob)
        local queen = RPD.MobFactory:mobByName('Warlock')
        queen:setPos(move_cells[2])
        RPD.setAi(queen, 'PASSIVE')
        RPD.Dungeon.level:spawnMob(queen)
        queen:getSprite():tint(destRank == 8 and 0xFF0000 or 0x0000FF, 0.5)
    end

    -- FIX: Castling - Ensure the piece that just moved is actually a King
    if castleMoves[move_str] and destMob and destMob:getEntityKind() == 'King' then
        local rookMove = rookMoves[move_str]
        local cells = { cellFromChessCell(string.sub(rookMove, 1, 2)),
                        cellFromChessCell(string.sub(rookMove, 3, 4)) }
        movePiece(cells[1], cells[2])
    end

    -- caveman: en passant. captured pawn beside destination, remove it.
    if isEnPassant then
        local pawnCell = pawnVictim[move_str]
        local cell = cellFromChessCell(pawnCell)
        local mob = RPD.Actor:findChar(cell)
        if mob then
            mob:die(mob)
        end
    end
end

local function highlightCells(cells)
    RPD.Sfx.HighlightCell:removeAll()

    for k, cell in pairs(cells) do
        local pos = cellFromChessCell(cell)
        RPD.Sfx.HighlightCell:add(pos)
    end
end

local gameInProgress = true

local function processLose()
    RPD.glog("You Lose!")
    restorePets()
    RPD.Dungeon.hero:die(RPD.Dungeon.hero)
    gameInProgress = false
end

local function processWin()
    restorePets()
    local mobs = RPD.Dungeon.level.mobs
    local iterator = mobs:iterator()
    local mobsToDie = {}

    while iterator:hasNext() do
        local mob = iterator:next()
        -- FIX: Prevent mass-extinction of pets/merchants. Only target chess pieces.
        local kind = mob:getEntityKind()
        local isChessPiece = false
        for _, pieceName in pairs(pieces_set) do
            if pieceName == kind then
                isChessPiece = true
                break
            end
        end

        if isChessPiece then
            table.insert(mobsToDie, mob)
        end
    end

    for i,mob in ipairs(mobsToDie) do
        mob:die(RPD.Dungeon.hero)
    end

    RPD.glog("You Win!")

    local level = RPD.Dungeon.level
    local origin = level:getProperty("chessBoardOrigin", "")

    -- caveman: prize chest at board centre (both paths).
    local centerCell = cellFromChessCell("e4")
    local prize = RPD.ItemFactory:itemByName("WandOfFirebolt")
    local heap = level:drop(prize, centerCell)
    heap.type = RPD.Heap.Type.CHEST
    heap.sprite:drop(centerCell)

    if origin and origin ~= "" then
        -- caveman: CityBossLevel. King defeated via chess. Java clears board + badge + unlocks exit.
        level:onChessWin()
    else
        -- caveman: chess_level debug. fill chasm ring + exit portal to town.
        for x = 3, 12 do
            for y = 3, 12 do
                level:set(level:cell(x, y), RPD.Terrain.EMPTY)
            end
        end
        RPD.GameScene:updateMap()

        RPD.createLevelObject(
                {kind = "PortalGateSender", target = {levelId = "town_2", x = 12, y = 28}},
                cellFromChessCell("e2")
        )
    end

    gameInProgress = false
end

local AI_DELAY_MS = 800
local aiMoveAt = 0
local allowedMoves = {}

local function getPiece(board, engineCell)
    return string.sub(board, engineCell+1, engineCell + 1)
end

return actor.init({
    act = function()
        return true
    end,

    onStep = function()
        if #scheduledMoves > 0 then
            if RPD.SystemTime:now() - aiMoveAt >= AI_DELAY_MS then
                local m = scheduledMoves[1]
                animateMove(m[1], m[2], m[3])

                -- FIX: Process delayed win/loss so the final move is visible
                local match_end = m[4]
                table.remove(scheduledMoves, 1)

                if match_end == "win" then
                    processWin()
                elseif match_end == "lose" then
                    processLose()
                end
            end
        end
    end,

    actionTime = function()
        return 0.1
    end,

    activate = function(data)
        RPD.Dungeon.hero:interrupt()

        -- caveman: ask Java where board a8 cell is. refresh every activate (level may differ).
        -- default 4,4 = chess_level debug level. CityBossLevel returns the carved hall board.
        local lvl = RPD.Dungeon.level
        -- caveman: ask Java where board a8 cell is (via level property). default 4,4 = chess_level.
        local origin = tonumber(lvl:getProperty("chessBoardOrigin", ""))
        if origin and origin >= 0 then
            x0 = lvl:cellX(origin)
            y0 = lvl:cellY(origin)
        else
            x0 = 4
            y0 = 4
        end

        -- caveman: save/load. if data (serialized state from ScriptedActor), restore sunfish.
        -- pieces already exist as saved mobs — don't respawn.
        if data and data ~= "" then
            chess = sunfish.new()
            local parts = util.split(data, "\n")
            chess.board = parts[1] or chess.board
            chess.score = tonumber(parts[2]) or 0
            chess.wc = { parts[3]:sub(1,1) == "T", parts[3]:sub(2,2) == "T" }
            chess.bc = { parts[4]:sub(1,1) == "T", parts[4]:sub(2,2) == "T" }
            chess.ep = tonumber(parts[5]) or 0
            chess.kp = tonumber(parts[6]) or 0
            gameInProgress = true
            move_str = ''
            scheduledMoves = {}
            allowedMoves = {}
        elseif not chess then
            gameInProgress = true
            move_str = ''
            scheduledMoves = {}
            allowedMoves = {}
            chess = sunfish.new()
            pieces = {}

            -- caveman: freeze hero pets so they not walk board / kill pieces / get captured.
            -- save their ai tag now, restore when game ends (processWin / processLose).
            frozenPets = {}
            local mobsIter = RPD.Dungeon.level.mobs:iterator()
            while mobsIter:hasNext() do
                local mob = mobsIter:next()
                if mob:isPet() then
                    frozenPets[#frozenPets + 1] = { mob = mob, tag = mob:getState():getTag() }
                    RPD.setAi(mob, "PASSIVE")
                end
            end

            local level = RPD.Dungeon.level

            local boardData = util.split(chess.board, "\n")
            for i, v in ipairs(boardData) do
                print(v)
                if i >= 3 and i <= 10 then
                    local y = i - 2
                    local cell = cellFromChess(0, y)

                    for ii = 1, 8 do
                        local chessCell = chessCellFromCell(cell)
                        local piece = string.sub(v, ii + 1, ii + 1)

                        if pieces_set[piece] then
                            local mob = RPD.MobFactory:mobByName(pieces_set[piece])

                            mob:setPos(cell)
                            RPD.setAi(mob, "PASSIVE")
                            level:spawnMob(mob)

                            if piece == piece:upper() then
                                mob:getSprite():tint(0xFF0000, 0.5)
                            else
                                mob:getSprite():tint(0x0000FF, 0.5)
                            end

                            pieces[chessCell] = mob
                        end
                        cell = cell + 1
                    end
                end
            end
        end
    end,

    cellClicked = function(cell)

        if not gameInProgress then
            return false
        end

        RPD.Dungeon.hero:interrupt()

        -- FIX: added local
        local chessCell = chessCellFromCell(cell)

        if not chessCell then
            RPD.glog("Click on the board — it is your move, Hero")
            return true
        end

        -- FIX: added local
        local engineCell = sunfish.cell_2_move(chessCell)

        RPD.Sfx.HighlightCell:removeAll()

        if string.len(move_str) == 0 then

            -- FIX: Ignore empty cells / enemy piece clicks when starting a selection
            local clickedPiece = getPiece(chess.board, engineCell)
            if not string.match(clickedPiece, "%u") then
                return true
            end

            move_cells[1] = cell
            player_chess_cells[1] = chessCell
            move_str = chessCell

            allowedMoves = {}

            local pseudoMoves = chess:genMoves()
            local moveCandidates = {}

            for i, v in ipairs(pseudoMoves) do
                if sunfish.move_2_cell(v[1]) == chessCell then
                    local validMove = true
                    local probe_move_str = sunfish.move_2_cell(v[1]) .. sunfish.move_2_cell(v[2])

                    local probe = sunfish.move(chess, probe_move_str)
                    local probeMoves = probe:genMoves()

                    for ii, vv in ipairs(probeMoves) do
                        local target = getPiece(probe.board, vv[2])
                        if target == 'k' then
                            validMove = false
                        end
                    end

                    if validMove then
                        allowedMoves[sunfish.move_2_cell(v[2])] = true
                        table.insert(moveCandidates, v)
                    end
                end
            end

            local selectedMob = RPD.Actor:findChar(move_cells[1])
            if selectedMob then
                selectedMob:getSprite():emitter():burst(RPD.Sfx.ElmoParticle.FACTORY, 4)
            end

            local hCells = { chessCell }
            for i, candidate in ipairs(moveCandidates) do
                table.insert(hCells, sunfish.move_2_cell(candidate[2]))
            end
            highlightCells(hCells)
        else

            -- FIX: added local
            local clickedPiece = getPiece(chess.board, engineCell)
            if string.match(clickedPiece,"%u") then
                -- Re-selecting own piece. Reset and require another click.
                move_str = ''
                RPD.Sfx.HighlightCell:removeAll()
                return true
            end

            if not allowedMoves[chessCell] then
                RPD.glog("illegal move: %s", chessCell)
                -- FIX: Don't lock out the player, reset the attempt!
                move_str = ''
                RPD.Sfx.HighlightCell:removeAll()
                return true
            end

            move_str = move_str .. chessCell
            move_cells[2] = cell
            player_chess_cells[2] = chessCell

            local moveResult = sunfish.move(chess, move_str)

            if moveResult then
                chess = moveResult:rotate()

                RPD.Sfx.HighlightCell:removeAll()
                animateMove(move_str, move_cells, player_chess_cells)

                local score
                -- FIX: Added local ai_move
                local ai_move
                chess, ai_move, score = sunfish.ai_move(chess:rotate())

                -- FIX: Let the move animate before triggering Win/Lose
                local match_end = nil
                if score <= -sunfish.MATE_VALUE then match_end = "win" end
                if score >= sunfish.MATE_VALUE then match_end = "lose" end
                if #chess:genMoves() == 0 then match_end = "lose" end

                -- Safety check: If AI couldn't generate a move, bypass the animation queue
                if not ai_move then
                    if match_end == "win" then processWin() end
                    if match_end == "lose" then processLose() end
                    return true
                end

                local ai_target_chess_cells = { string.sub(ai_move, 1, 2), string.sub(ai_move, 3, 4) }
                -- FIX: added local
                local ai_cells = { cellFromChessCell(ai_target_chess_cells[1]), cellFromChessCell(ai_target_chess_cells[2]) }

                -- Push the Match status to element 4 so it fires AFTER the piece visually lands
                table.insert(scheduledMoves, { ai_move, ai_cells, ai_target_chess_cells, match_end })
                aiMoveAt = RPD.SystemTime:now()

            else
                RPD.glog('illegal move')
            end
            move_str = ''
        end

        return true
    end,

    -- caveman: serialize sunfish state for save/load. ScriptedActor calls this on save.
    serialize = function()
        if not chess then return "" end
        return chess.board .. "\n" ..
               tostring(chess.score) .. "\n" ..
               (chess.wc[1] and "T" or "F") .. (chess.wc[2] and "T" or "F") .. "\n" ..
               (chess.bc[1] and "T" or "F") .. (chess.bc[2] and "T" or "F") .. "\n" ..
               tostring(chess.ep) .. "\n" ..
               tostring(chess.kp)
    end
})