---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 9,
            imageFile = "items/swords.png",
            name      = "BoneSaw_Name",
            info      = "BoneSaw_Info",
            price     = 20,
            equipable = RPD.Slots.weapon
        }
    end,

    goodForMelee = function()
        return true
    end,

    getVisualName = function()
        return "BoneSaw"
    end,

    getAttackAnimationClass = function()
        return "sword"  --look at KindOfWeapon.java for possible values
    end,

    slot = item.slot_bothHands,

    requiredSTR = function(self, item)
        return 9
    end,

    info = function(self, item)
        local lvl = item:level()
        local hero = item:getOwner()
        local user_level = hero:skillLevel()

        local dmgMin = (user_level + lvl) * (2 + lvl)
        local dmgMax = (user_level + lvl) * (3 + lvl * 2)
        local avg = dmgMin + math.floor((dmgMax - dmgMin) / 2)

        local text = RPD.textById("BoneSaw_Info")
        text = text .. "\n\n" .. RPD.format(RPD.textById("MeleeWeapon_Info2a"), avg)
        if self:requiredSTR(item) > hero:effectiveSTR() then
            text = text .. "\n\n" .. RPD.textById("MeleeWeapon_Info2c")
        end
        return text
    end,

    accuracyFactor    = function(self, item, user)
        local lvl = item:level()
        local user_level = user:skillLevel()
        -- STR deficit bites like Weapon.accuracyFactor: /1.5^n accuracy
        local encumbrance = math.max(self:requiredSTR(item) - user:effectiveSTR(), 0)
        return (1 + (lvl + user_level) * 0.15) / math.pow(1.5, encumbrance)
    end,

    damageRoll        = function(self, item, user)
        local lvl = item:level()
        local user_level = user:skillLevel()
        return (user_level + lvl) * math.random(2 + lvl, 3 + lvl*2)
    end,

    attackDelayFactor = function(self, item, user)
        local lvl = item:level()
        local user_level = user:skillLevel()
        -- STR deficit bites like Weapon.attackDelayFactor: *1.2^n delay
        local encumbrance = math.max(self:requiredSTR(item) - user:effectiveSTR(), 0)
        return math.max(1 - (lvl + user_level) * 0.05, 0.25) * math.pow(1.2, encumbrance)
    end,

    attackProc        = function(self, item, attacker, defender, damage)
        RPD.affectBuff(defender,"Bleeding",3)

        -- Check if attacker is a Doctor and if this is a critical hit
        local isDoctor = attacker:getHeroClass():getEntityKind() == "DOCTOR"

        -- Calculate attack and defense skills to determine if it's a critical hit
        local attackSkill = attacker:attackSkill(defender)
        local defenseSkill = defender:defenseSkill(attacker)

        -- Generate random rolls similar to Java implementation
        local acuRoll = math.random() * attackSkill
        local defRoll = math.random() * defenseSkill

        -- A critical hit occurs when the attack roll significantly exceeds the defense roll
        local isCriticalHit = acuRoll > defRoll * 3

        -- Apply critical hit bonus if applicable
        local finalDamage = damage
        if isCriticalHit then
            finalDamage = damage * 1.5  -- 50% damage bonus for critical hits
        end

        -- Handle critical hit effects for Doctor class - drop extra parts
        -- (constructs and non-corporeal foes have nothing dissectable)
        if isCriticalHit and isDoctor and defender:hasBodyParts() then
            -- Create random harvestable items to drop
            local harvestItems = {"ToxicGland", "RottenOrgan", "BoneShard"}
            local randomItem = harvestItems[math.random(1, #harvestItems)]

            local itemToDrop = RPD.ItemFactory:itemByName(randomItem)
            if itemToDrop then
                RPD.Dungeon.level:animatedDrop(itemToDrop, defender:getPos())
            end
        end

        -- Apply 50% damage bonus against paralyzed foes if attacker is Doctor
        if defender.paralysed and isDoctor then
            finalDamage = finalDamage * 2
        end

        return finalDamage
    end,

    typicalSTR = function(self, item)
        return 9
    end
}
