---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Plague Doctor Harvesting System
--- DateTime: Implementation for Plague Doctor alchemy system
---

local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

return item.init{
    desc  = function ()
        return {
            image     = 5,
            imageFile = "items/materials.png",
            name      = "BoneShard_Name",
            info      = "BoneShard_Info",
            price     = 5,
            stackable = true
        }
    end
}