---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 8:29 PM
---


local RPD = require "scripts/lib/commonClasses"

local item = require "scripts/lib/item"

local Accessory = luajava.bindClass("com.nyrds.pixeldungeon.items.accessories.Accessory")

return item.init{
    desc  = function ()
        return {
            image     = 26,
            imageFile = "items/artifacts.png",
            name      = "PlagueDoctorMask_Name",
            info      = "PlagueDoctorMask_Info",
            price     = 20,
            equipable = RPD.Slots.artifact
        }
    end,

    activate = function(self, item, hero)
        local mask = Accessory:getByName("PlagueDoctorMask")
        mask:equip(true)
        RPD.permanentBuff(hero, "GasesImmunity")
    end,

    deactivate = function(self, item, hero)
        Accessory:unequip()
        -- the class armor has its own beaked mask: immunity lives while either source is worn
        local armor = hero:getBelongings():getItemFromSlot(RPD.Slots.armor)
        if armor:getEntityKind() ~= "DoctorArmor" then
            RPD.removeBuff(hero, "GasesImmunity")
        end
    end
}
