---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/2/20 12:24 AM
---

local RPD = require "scripts/lib/commonClasses"

local gameScene = require "scripts/services/gameScene"

local service = {}

service.onStep = function(self, scene)
    if scene == "GameScene" then
        gameScene.onStep()
    end
end


return service