---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/warrior.png",
            name          = "ArmorMastery_Name",
            info          = "ArmorMastery_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, caster, cell)
        RPD.topEffect(caster:getPos(),"body_armor")

        RPD.affectBuff(caster,"DefenceMastery", 20)

        return true
    end
}
