---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 0,
            imageFile     = "spellsIcons/warrior.png",
            name          = "BodyArmorSpell_Name",
            info          = "BodyArmorSpell_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = 1,
            spellCost     = 5,
            cooldown      = 20,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, caster, cell)
        RPD.topEffect(caster:getPos(),"body_armor")

	    RPD.playSound("body_armor")
        local buff = RPD.affectBuff(caster,"BodyArmor", 15+10*caster:skillLevel())
        buff:level(caster:skillLevel())

        return true
    end
}
