---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/24/21 6:39 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Calm_Name",
            info          = "Calm_Info",
            magicAffinity = "Huntress",
            targetingType = "char",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    castOnChar = function(self, spell, caster, chr)

        RPD.affectBuff(chr, RPD.Buffs.Sleep, caster:skillLevel()):setSource(caster)

        return true
    end
}