---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/24/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/hunting.png",
            name          = "CharmSpell_Name",
            info          = "CharmSpell_Info",
            magicAffinity = "Huntress",
            targetingType = "char_not_self",
            level         = 2,
            castTime      = 0,
            spellCost     = 3
        }
    end,

    castOnChar = function(self, spell, caster, chr)

        RPD.affectBuff(chr, "Charm", math.sqrt(caster:skillLevel() * caster:lvl()) + 5 ):setSource(caster)

        return true
    end
}