---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:08
---

local spells = {}
spells["Necromancy"] = {"RaiseDead","Exhumation", "DarkSacrifice","Possess"}
spells["Common"] = {"TownPortal","Heal","RaiseDead","Cloak","Calm","Charm"}

spells["Combat"] = {"DieHard","Dash","BodyArmor","Smash"}
spells["Rogue"] = {"Cloak","Backstab","KunaiThrow","Haste"}
spells["Witchcraft"] = {"Roar","LightningBolt","Heal","Order"}
spells["Huntress"] = {"Calm","Charm","ShootInEye","SummonBeast"}
spells["Elf"] = {"MagicArrow","Sprout","HideInGrass","NatureArmor"}

return spells