---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/warrior.png",
            name          = "DashSpell_Name",
            info          = "DashSpell_Info",
            magicAffinity = "Combat",
            targetingType = "cell",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    castOnCell = function(self, spell, chr, cell)

        local level = chr:level()

        local ownPos = chr:getPos()

        local dist = level:distance(ownPos, cell)

        if ownPos == cell then
            RPD.glogn("DashSpell_OnSelf")
            return false
        end

        if dist  > 2 then
            RPD.glogn("DashSpell_TooFar")
            return false
        end

        local dst = RPD.Ballistica:cast(ownPos, cell, false, true, true)
        RPD.glogp("dash to: %d", dst)

        local char = RPD.Actor:findChar(dst)

        if char then
            local newPos = char:getPos()
            if char:push(chr) then
                dst = newPos
                RPD.glogp("dash to: %d", dst)

            end
        end

        local object = level:getLevelObject(dst)

        if object then
            local newPos = object:getPos()
            if object:push(chr) then
                dst = newPos
                RPD.glogp("dash to: %d", dst)

            end
        end

        RPD.zapEffect(ownPos,dst,"dash")
        RPD.blinkTo(chr,dst)

        return true
    end
}
