---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/warrior.png",
            name          = "Dash_Name",
            info          = "Dash_Info",
            magicAffinity = "Combat",
            targetingType = "cell",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    castOnCell = function(self, spell, chr, cell)
        RPD.zapEffect(chr:getPos(),cell,"dash")
        --RPD.blinkTo(chr,cell)
        return true
    end
}
