---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 0,
            imageFile     = "spellsIcons/warrior.png",
            name          = "DieHard_Name",
            info          = "DieHard_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, caster, cell)
        local duration = 20 --caster:skillLevel() * 20

        RPD.affectBuff(caster,"DieHard", duration)

        --attach visual stuff
        local emitter = caster:getSprite():emitter()
        emitter:pour(RPD.speckEffectFactory(RPD.Sfx.Speck.HEALING,RPD.Sfx.Speck.UP), duration)

        return true
    end
}
