---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

local spellLevel = 2

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/warrior.png",
            name          = "DieHardSpell_Name",
            info          = "DieHardSpell_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = spellLevel,
            spellCost     = 5,
            cooldown      = 50,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, caster, cell)

        local buffLevel = math.min(3, caster:skillLevel()-spellLevel) + 2

        local duration = buffLevel * 20 + 20

        local buff = RPD.affectBuff(caster,"DieHard", duration)
        buff:level(buffLevel)

        return true
    end
}
