---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 28.07.18 23:42
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/rogue.png",
            name          = "Haste_Name",
            info          = "Haste_Info",
            magicAffinity = "Rogue",
            targetingType = "self",
            level         = 3,
            castTime      = 0,
            spellCost     = 10
        }
    end,

    cast = function(self, spell, caster)
        caster:spend(-caster:skillLevel()/2)
        return true
    end
}