---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Heal_Name",
            info          = "Heal_Info",
            magicAffinity = "Witchcraft",
            targetingType = "char",
            level         = 2,
            castTime      = 1,
            spellCost     = 5,
            cooldown      = 2
        }
    end,

    castOnChar = function(self, spell, caster, target)
        if target then
            local heal = target:ht() / 5. * caster:skillLevel()
            target:heal(math.max(1, heal), caster)
        end
        return true
    end
}