---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Heal_Name",
            info          = "Heal_Info",
            magicAffinity = "Witchcraft",
            targetingType = "cell",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    castOnCell = function(self, spell, caster, cell)
        local target = RPD.Actor:findChar(cell)

        if target then
            RPD.glogn("Heal_NeedChar")
            return false
        end

        if target then

            local heal = target:ht() / 5. * caster:skillLevel()
            target:heal(math.max(1, heal))
        end

    end
}