---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "LightningBolt_Name",
            info          = "LightningBolt_Info",
            magicAffinity = "Witchcraft",
            targetingType = "cell",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    castOnCell = function(self, spell, caster, cell)

        local target = RPD.Actor:findChar(cell)

        if target then
            RPD.glogn("LightningBolt_NeedChar")
            return false
        end

        local damage = math.random(caster:lvl(),caster:skillLevel() * caster:lvl())
        RPD.CharUtils:lightningProc(target, damage)

        return true
    end
}