---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 10:56 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 0,
            imageFile     = "spellsIcons/naturegift.png",
            name          = "MagicArrow_Name",
            info          = "MagicArrow_Info",
            magicAffinity = "Elf",
            targetingType = "char_not_self",
            level         = 1,
            castTime      = 0.1,
            spellCost     = 5,
            cooldown      = 1
        }
    end,

    castOnChar = function(self, spell, caster, victim)

        RPD.zapEffect(caster:getPos(),victim:getPos(),"magic_arrow")
        victim:damage(math.random(1,caster:ht()/2), caster)

        return true
    end
}