---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Order_Name",
            info          = "Order_Info",
            magicAffinity = "Witchcraft",
            targetingType = "char_not_self",
            level         = 3,
            castTime      = 1,
            spellCost     = 10
        }
    end,

    castOnChar = function(self, spell, caster, target)

        if not target:canBePet() then
            target:yell("Order_Resist")
            return false
        end

        target:execute(caster, RPD.Actions.ch_order)

        return true
    end
}