---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Order_Name",
            info          = "Order_Info",
            magicAffinity = "Witchcraft",
            targetingType = "self",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    cast = function(self, spell, caster)
        return true
    end
}