---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "Order_Name",
            info          = "Order_Info",
            magicAffinity = "Witchcraft",
            targetingType = "cell",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    castOnCell = function(self, spell, caster, cell)

        local target = RPD.Actor:findChar(cell)

        if not target then
            caster:yell("Order_NeedChar")
            return false
        end

        if not target:canBePet() then
            target:yell("Order_Resist")
            return false
        end

        target:execute(caster, RPD.Actions.ch_order)

        return true
    end
}