---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 12:06 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 0,
            imageFile     = "spellsIcons/hunting.png",
            name          = "ShootInEye_Name",
            info          = "ShootInEye_Info",
            magicAffinity = "Huntress",
            targetingType = "char",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    castOnChar = function(self, spell, caster, tgt)
        RPD.zapEffect(caster:getPos(),tgt:getPos(),"Boomerang")
        RPD.affectBuff(tgt, RPD.Buffs.Blindness, caster:skillLevel())
        tgt:damage(math.max(math.random(1,tgt:ht()/2),caster:ht()), caster)
        return true
    end
}