---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 12:06 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 0,
            imageFile     = "spellsIcons/hunting.png",
            name          = "ShootInEye_Name",
            info          = "ShootInEye_Info",
            magicAffinity = "Huntress",
            targetingType = "char_not_self",
            level         = 1,
            castTime      = 1,
            spellCost     = 5
        }
    end,

    castOnChar = function(self, spell, caster, victim)
        RPD.zapEffect(caster:getPos(),victim:getPos(),"Boomerang")
        RPD.affectBuff(victim, RPD.Buffs.Blindness, caster:skillLevel())

        local weapon = caster:getBelongings().weapon
        local damage = math.sqrt(caster:skillLevel()) * weapon:damageRoll(caster)

        victim:damage(damage, caster)
        RPD.Sfx.Wound:hit(victim)

        return true
    end
}