---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/warrior.png",
            name          = "SmashSpell_Name",
            info          = "SmashSpell_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, chr)
        local items = chr:getBelongings()

        if items.weapon == nil then
            RPD.glogn("SmashSpell_NeedWeapon")
            return false
        end

        local fist = RPD.topEffect(chr:getPos(),"smash_fist")
        fist:incY(10);
        RPD.attachMoveTweener(fist, 0,0,1)

        local clip = RPD.bottomEffect(chr:getPos(),"smash_blast")
        clip:setScale(1.5,1.3)

        local function smash(cell)
            local victim = RPD.Actor:findChar(cell)
            if victim ~= nil then
                RPD.affectBuff(victim, RPD.Buffs.Vertigo, chr:skillLevel())
                local dmg = items.weapon:damageRoll(chr)
                dmg = victim:defenseProc(chr, dmg)
                victim:damage(dmg, chr)
            end
        end

	    RPD.playSound("smash.mp3")
        RPD.forCellsAround(chr:getPos(), smash)
	
        return true
    end
}
