---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:57
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/warrior.png",
            name          = "Smash_Name",
            info          = "Smash_Info",
            magicAffinity = "Combat",
            targetingType = "self",
            level         = 1,
            spellCost     = 1,
            cooldown      = 1,
            castTime      = 0.5
        }
    end,
    cast = function(self, spell, chr)
        local items = chr:getBelongings()

        if items.weapon == nil then
            RPD.glogn("Need weapon to smash")
            return false
        end

        local function forCellsAround(cell, action)
            local x = RPD.Dungeon.level:cellX(cell)
            local y = RPD.Dungeon.level:cellY(cell)

            for i = x - 1, x + 1 do
                for j = y - 1, y + 1 do
                    if i~=x or j~=y then
                        action(RPD.Dungeon.level:cell(i,j))
                    end
                end
            end
        end

        local function smash(cell)

            RPD.topEffect(chr:getPos(),"smash_fist")

            local clip = RPD.bottomEffect(chr:getPos(),"smash_blast")
            clip:setScale(1.5,1.3)

            local victim = RPD.Actor:findChar(cell)
            if victim ~= nil then
                RPD.affectBuff(victim, RPD.Buffs.Vertigo, chr:skillLevel())
                local dmg = items.weapon:damageRoll(chr)
                dmg = victim:defenseProc(chr, dmg)
                victim:damage(dmg, chr)
            end
        end

	RPD.playSound("smash.mp3")
        forCellsAround(chr:getPos(), smash)
	
        return true
    end
}
