---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 10:59 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


local seeds = {"Earthroot.Seed",
               "Firebloom.Seed",
               "Sungrass.Seed",
               "Dreamweed.Seed",
               "Sorrowmoss.Seed",
               "Icecap.Seed",
               "Fadeleaf.Seed"}

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/naturegift.png",
            name          = "Sprout_Name",
            info          = "Sprout_Info",
            magicAffinity = "Elf",
            targetingType = "cell",
            level         = 2,
            castTime      = 0.1,
            spellCost     = 1
        }
    end,

    castOnCell = function(self, spell, caster, cell)

        RPD.placeBlob(RPD.Blobs.Regrowth, caster:level() * 10)

        RPD.forCellsAround(cell, function(cell)
            if caster:skillLevel() > math.random(1, RPD.Dungeon.depth) then
                local seed = seeds[math.random(1, #seeds)]
                RPD.createItem(seed):couch(cell)
            end
            return true
        end)

        return true
    end
}