---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 12:16 AM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

local beasts = {"Rat", "Crab", "Swarm", "Bat", "Spinner", "Scorpio", "Worm"}

return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/hunting.png",
            name          = "SummonBeast_Name",
            info          = "SummonBeast_Info",
            magicAffinity = "Huntress",
            targetingType = "self",
            level         = 1,
            castTime      = 0,
            spellCost     = 1
        }
    end,

    cast = function(self, spell, caster)
        RPD.forCellsAround(caster:getPos(), function(cell)
            if not RPD.Actor:findChar(cell) then
                local beast = beasts[math.min(1,math.max(math.random(caster:skillLevel()/2, caster:skillLevel()), #beasts))]
                RPD.spawnMob(beast, cell):makePet(caster)
            end

        end)

        return true
    end
}