---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/23/20 11:28 PM
---

local RPD                 = require "scripts/lib/commonClasses"
local spell               = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/common.png",
            imageSize     = 32,
            name          = "TestSpell_Name",
            info          = "TestSpell_Info",
            magicAffinity = "Test",
            targetingType = "self",
            level         = 1,
            castTime      = 1,
            spellCost     = 0
        }
    end,

    cast = function(self, spell, caster)
        return true
    end
}