---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/23/20 11:28 PM
---

local RPD                 = require "scripts/lib/commonClasses"
local spell               = require "scripts/lib/spell"

local distracted          = {}
distracted["PASSIVE"]     = true
distracted["SLEEPING"]    = true
distracted["FLEEING"]     = true
distracted["HORRIFIED"]   = true
distracted["RUNNINGAMOK"] = true

return spell.init{
    desc  = function ()
        return {
            image         = 2,
            imageFile     = "spellsIcons/common.png",
            imageSize     = 32,
            name          = "Backstab_Name",
            info          = "Backstab_Info",
            magicAffinity = "Rogue",
            targetingType = "self",
            level         = 1,
            castTime      = 1,
            spellCost     = 0
        }
    end,

    cast = function(self, spell, caster)
        return true
    end
}