--
-- User: Logodum
-- Date: 16.12.2021
-- Time: 15:50
-- Generated by EmmyLua(https://github.com/EmmyLua)
-- This file is part of Remixed Pixel Dungeon.
--

local RPD = require "scripts/lib/commonClasses"
local ai = require "scripts/lib/ai"

return ai.init({
    act = function(self, ai, me)
        me:spend(1)
    end,
    
    gotDamage = function(self, me, src, dmg)
    end,

    status = function(self, ai, me)
        return "None"
    end
})