---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"

local actor = require "scripts/lib/actor"

return actor.init({
    act = function()
        local hero = RPD.Dungeon.hero
        local belongings = hero.belongings

        if belongings.weapon then
            RPD.Dungeon.level:setCompassTarget(26,24)
        else
            RPD.Dungeon.level:setCompassTarget(15,19)
        end

        return true
    end,
    actionTime = function()
        return 1
    end,
    activate = function()

    end
})