---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/9/22 1:15 AM
---

local RPD = require "scripts/lib/commonClasses"

local interlevelScene = {}


tilesChoiceWindowShown = false

--! Called when interlevelScene enters static mode
interlevelScene.onStep = function(mode, done)
    if not done then
        return false
    end
    if mode == "DESCEND" and RPD.Dungeon.level.levelId == '1' and RPD.ModdingMode:inRemixed() then
        RPD.RemixedDungeon:scene():enumerateWindows()
        local activeWindow = RPD.RemixedDungeon:scene():getWindow(0)
        RPD.debug("activeWindow :%s", tostring(activeWindow))
        if not tilesChoiceWindowShown then
            if activeWindow == nil then
                local wnd = RPD.new("com.nyrds.pixeldungeon.windows.WndTilesKind")
                if not wnd:shownBefore() then
                    RPD.RemixedDungeon:scene():add(wnd)
                end
                tilesChoiceWindowShown = true
            end
        else
            if activeWindow == nil then
                return true
            end
        end
    else
        return true
    end
end


return interlevelScene