---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/9/22 1:15 AM
---

local RPD = require "scripts/lib/commonClasses"

local interlevelScene = {}

img = RPD.new('com.watabou.noosa.Image','ui/title.png',0,0,148,128)

--! Called when interlevelScene enters static mode
interlevelScene.onStep = function(mode, done)

    RPD.RemixedDungeon:scene():remove(img)
    RPD.RemixedDungeon:scene():add(img)
    img:setPos(0,10)

    if not done then
        return false
    end

    return true
end


return interlevelScene