---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/9/22 1:15 AM
---

local RPD = require "scripts/lib/commonClasses"

local interlevelScene = {}


tilesChoiceWindowShown = false

--! Called when interlevelScene enters static mode
interlevelScene.onStep = function(mode, done)
    if done and mode == "DESCEND" then
        RPD.RemixedDungeon:scene():enumerateWindows()
        local activeWindow = RPD.RemixedDungeon:scene():getWindow(0)
        RPD.debug("activeWindow :%s", tostring(activeWindow))
        if not tilesChoiceWindowShown then
            if activeWindow == nil then
                local wnd = RPD.new("com.nyrds.pixeldungeon.windows.WndTilesKind")
                RPD.RemixedDungeon:scene():add(wnd)
                tilesChoiceWindowShown = true
            end
        else
            if activeWindow == nil then
                return true
            end
        end
    end
end


return interlevelScene