---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/6/21 1:43 AM
---


local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/witchcraft.png",
            name          = "LightningBolt_Name",
            info          = "LightningBolt_Info",
            magicAffinity = "Witchcraft",
            targetingType = "char_not_self",
            level         = 2,
            castTime      = 1,
            spellCost     = 5,
            cooldown      = 2
        }
    end,

    castOnChar = function(self, spell, caster, victim)
        local lvl = caster:lvl()
        local damage = math.random(lvl,caster:skillLevel() * math.sqrt(lvl) + lvl)
        RPD.CharUtils:lightningProc(caster, victim:getPos(), damage)

        return true
    end
}