---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/26/21 10:07 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"

return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/naturegift.png",
            name          = "NatureArmorSpell_Name",
            info          = "NatureArmorSpell_Info",
            magicAffinity = "Elf",
            targetingType = "self",
            level         = 1,
            spellCost     = 5,
            cooldown      = 20,
            castTime      = 0.5
        }
    end,

    cast = function(self, spell, caster)
        RPD.topEffect(caster:getPos(),"cloak")

        RPD.affectBuff(caster, RPD.Buffs.Barkskin, caster:skillLevel() * caster:lvl())
        return true
    end}
