---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/25/21 10:59 PM
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


local seeds = {"Earthroot.Seed",
               "Firebloom.Seed",
               "Sungrass.Seed",
               "Dreamweed.Seed",
               "Sorrowmoss.Seed",
               "Icecap.Seed",
               "Fadeleaf.Seed"}

return spell.init{
    desc  = function ()
        return {
            image         = 1,
            imageFile     = "spellsIcons/naturegift.png",
            name          = "Sprout_Name",
            info          = "Sprout_Info",
            magicAffinity = "Elf",
            targetingType = "cell",
            level         = 2,
            castTime      = 0.1,
            spellCost     = 5
        }
    end,

    castOnCell = function(self, spell, caster, cell)

        RPD.placeBlob(RPD.Blobs.Regrowth, cell, caster:skillLevel() * 10)

        local level = caster:level()

        RPD.forCellsAround(cell, function(cell)
            if not level.passable[cell+1] then
                return
            end

            if not level:isPlainTile(cell) then
                return
            end

            if caster:lvl()/(RPD.Dungeon.depth + 1) > math.random() then
                local seed = seeds[math.random(1, #seeds)]
                level:plant(RPD.createItem(seed),cell)
            end
        end)

        return true
    end
}