---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 28.07.18 23:42
---

local RPD = require "scripts/lib/commonClasses"

local spell = require "scripts/lib/spell"


return spell.init{
    desc  = function ()
        return {
            image         = 3,
            imageFile     = "spellsIcons/common.png",
            name          = "TownPortal_Name",
            info          = "TownPortal_Info",
            magicAffinity = "Common",
            targetingType = "self",
            level         = 2,
            castTime      = 2,
            spellCost     = 3
        }
    end,
    cast = function(self, spell, caster)
        if caster:level():isBossLevel() then
            RPD.glogn("ScrollOfTeleportation_NoTeleport")
            return false
        end

        caster:setPortalLevelCoordinates(caster:getPosition())
        RPD.teleportTo("town_2", 15,11)
        return true
    end
}