---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/24/23 1:24 AM
---

local RPD = require "scripts/lib/commonClasses"

local mob = require"scripts/lib/mob"

return mob.init({
    damage = function(self,dmg,src)
        self:yell("Ouch!")
        self:setLayersMask(16)
    end
})

--return mob.init({})