---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/23/23 11:39 PM
---

local RPD = require "scripts/lib/commonClasses"
local mob = require "scripts/lib/mob"

return mob.init{
    defenceProc = function(self, enemy, dmg)
        RPD.affectBuff(enemy, "Ooze", self:skillLevel())
    end
}

--return mob.init({})