---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 7/5/21 1:40 AM
---

local RPD = require "scripts/lib/commonClasses"
local mob = require "scripts/lib/mob"

return mob.init{
    attackProc = function(self, enemy, dmg)
        if math.random() < 0.2 then
            RPD.affectBuff(enemy, "Vertigo", self:skillLevel())
        end
    end
}
