---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 24.03.19 18:35
---

local RPD = require "scripts/lib/commonClasses"

local serpent = require "scripts/lib/serpent"

local buff = {}

buff.__index = buff

function buff.attachTo(self, buff, target)
    return true
end

function buff.detach(self, buff)
    return true
end

function buff.act(self, buff)
    buff:detach()
    return true
end

function buff.saveData(self)
    return serpent.dump(self.data or {})
end

function buff.loadData(self, _, str)
    local _,data = serpent.load(str)
    self.data = data or {}
end

function buff.storeData(self, data)
    self.data = data or {}
end

function buff.restoreData(self)
    return self.data or {}
end

function buff.setProperty(self, key, value)
    self.data[key] = value
end

function buff.getProperty(self, key)
    return self.data[key]
end

function buff.defaultDesc()
    return {
        icon          = 0,
        name          = "custom buff",
        info          = "unconfigured custom buff",
    }
end

function buff.desc()
    return buff.defaultDesc()
end

function buff.buffDesc(self)
    local ret = buff.defaultDesc()
    local own = self:desc()

    self.data = own.data or {}

    for k,v in pairs(ret) do
        ret[k] = own[k] or v
    end

    return ret
end


buff.init = function(desc)
    setmetatable(desc, buff)

    desc.data = {}

    return desc
end

return buff