---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 12/26/19 1:19 AM
---

local util = {}


---@param tbl table
function util.clone_table(tbl)
    local ret = {}

    for k,v in pairs(tbl) do
        if type(v)=="table" then
            ret[k] = util.clone_table(v)
        else
            ret[k] = v
        end
    end
    return ret
end

return util