---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---

local buff = require "scripts/lib/buff"

return buff.init{
    desc  = function ()
        return {
            icon          = 45,
            name          = "BodyArmorBuff_Name",
            info          = "BodyArmorBuff_Info",
        }
    end,
    act = function(self,buff)
        buff:detach()
    end,
    drBonus = function(self,buff)
        return (buff.target:STR()-10) * (1 + 0.5 * buff:level()) -- use STR, applicable only to hero!
    end,
    speedMultiplier = function(self, buff)
        return 0.5
    end
}