---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---

local buff = require "scripts/lib/buff"
local RPD = require "scripts/lib/commonClasses"

return buff.init{
    desc  = function ()
        return {
            icon          = 45,
            name          = "BodyArmorBuff_Name",
            info          = "BodyArmorBuff_Info",
        }
    end,

    act = function(self,buff)
        buff:detach()
    end,

    drBonus = function(self,buff)
        local bonus = (buff.target:effectiveSTR()-10) * (1 + buff:level())
        return bonus
    end,

    speedMultiplier = function(self, buff)
        return 0.85
    end
}