---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/4/24 11:53 PM
---

local buff = require "scripts/lib/buff"

local RPD  = require "scripts/lib/commonClasses"

return buff.init{
    desc  = function ()
        return {
            icon          = -1,
            name          = "ChampionOfFireBuff_Name",
            info          = "ChampionOfFireBuff_Info",
        }
    end,


    attachTo = function(self, buff, target)
        self.data.activated = self.data.activated or false

        if target:hasBuff("ChampionOfFire") then
            return false
        end

        target:setGlowing(0xAA2222, 1.5)

        if not self.data.activated then
            self.data.activated = true
        end

        return true
    end,

    attackProc = function(self, buff, enemy, damage)
        RPD.affectBuff(enemy, "Burning", 3)
        return damage
    end,

    attackSkillBonus = function(self, buff)
        return buff.target:lvl()
    end
}