---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 1/4/24 11:53 PM
---

local buff = require "scripts/lib/buff"

local RPD  = require "scripts/lib/commonClasses"

return buff.init{
    desc  = function ()
        return {
            icon          = -1,
            name          = "ChampionOfEarthBuff_Name",
            info          = "ChampionOfEarthBuff_Info",
        }
    end,


    attachTo = function(self, buff, target)
        RPD.debug(tostring(buff) .. "storage: ")
        for k,v in pairs(self.data) do
            RPD.debug(tostring(buff) .. " " .. tostring(k) .. " " .. tostring(v))
        end

        self.data.activated = self.data.activated or false

        if target:hasBuff("ChampionOfEarth") then
            RPD.debug(tostring(buff) .. " already has buff")
            return false
        end

        if not self.data.activated then
            RPD.debug(tostring(buff) .. "activating buff")
            self.data.activated = true
            target:ht(target:ht() * 4)
        end

        return true
    end
}