---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:00
---


local buffs = {"BodyArmor",
               "DieHard",
               "Cloak",
               "Counter",
               "Shield"}

return buffs