---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 7/19/21 12:13 AM
---

local buff = require "scripts/lib/buff"
local RPD  = require "scripts/lib/commonClasses"

return buff.init{

    icon = function(self, buff)
        return 50
    end,

    name = function(self, buff)
        return "Encumbrance_Name"
    end,

    info = function(self, buff)
        return  RPD.format(
                    "Encumbrance_Info",
                    buff.target:
                    getBelongings():
                    encumbranceCheck():
                    name())
    end,

}