---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 12/21/19 11:56 PM
---

local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"

local gases = {"ToxicGas","Paralysis","Vertigo"}

return buff.init{
    desc  = function ()
        return {
            icon          = 25,
            name          = "GasImmuneBuff_Name",
            info          = "GasImmuneBuff_Info",
        }
    end,

    immunities = function(self, buff)
        return gases
    end

}