---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 5/7/21 10:41 PM
---

local buff = require "scripts/lib/buff"

local RPD  = require "scripts/lib/commonClasses"

return buff.init{
    desc  = function ()
        return {
            icon          = 49,
            name          = "ManaShieldBuff_Name",
            info          = "ManaShieldBuff_Info",
        }
    end,

    defenceProc = function(self, buff, enemy, damage)
        RPD.topEffect(buff.target:getPos(),"mana_shield_effect")
        RPD.playSound("body_armor")
        buff:detach()
        return 0
    end
}