---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 14.04.19 0:07
---

local buff = require "scripts/lib/buff"

local RegenerationDelay

return buff.init{
    desc  = function ()
        return {
            icon         = 3,
            name          = "Regeneration_Name",
            info          = "Regeneration_Info",
        }
    end,

    act = function(self, buff)
        local ch = buff.target

        if not ch:isAlive() then
            return
        end

        if not ch:isStarving() and ch:hp() < ch:ht() then
            ch:hp(ch:hp()+1)
        end

    end,

    attachTo = function(self, buff, target)
        if target:buffLevel("Regeneration") > 1 then
            return false
        end

        return true
    end
}