---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/20/19 10:35 PM
---

local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"


return buff.init{
    desc  = function ()
        return {
            icon          = 47,
            name          = "ShiledBuff_Name",
            info          = "ShieldBuff_Info",
        }
    end,

    icon = function(self, buff)
        if self.data.state then
            return 47
        end
        return 48
    end,

    name = function(self, buff)
        if self.data.state then
            return "ShiledBuffReady_Name"
        end
        return "ShiledBuffNotReady_Name"
    end,

    attachTo = function(self, buff, target)
        self.data.state = false
        return true
    end,

    act = function(self,buff)
        self.data.state = true
        buff:spend(10/buff:level())
    end,

    defenceProc = function(self, buff, enemy, damage)
        if self.data.state then
            RPD.topEffect(buff.target:getPos(),"shield_blocked")

            RPD.playSound("body_armor.mp3")

            self.data.state = false

            return damage / 2
        else
            RPD.topEffect(buff.target:getPos(),"shield_broken")

            RPD.playSound("body_armor.mp3")
            return damage / 1.2
        end
    end
}
