---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/20/19 10:35 PM
---

local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"


return buff.init{
    desc  = function ()
        return {
            icon          = 47,
            name          = "ShiledBuff_Name",
            info          = "ShieldBuff_Info",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    defenceProc = function(self, buff, enemy, damage)

        if math.random() > 0.5 then
            RPD.topEffect(buff.target:getPos(),"shield_blocked")

            RPD.playSound("body_armor.mp3")
            return damage/2
        else
            RPD.topEffect(buff.target:getPos(),"shield_broken")

            RPD.playSound("body_armor.mp3")
            return damage/2
        end
    end
}
