---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/20/19 10:35 PM
---

local RPD  = require "scripts/lib/commonClasses"

local buff = require "scripts/lib/buff"

return buff.init{
    icon = function(self, buff)
        return 1
    end,

    name = function(self, buff)
        return "Test buff"
    end,

    defenceProc = function(self, buff, enemy, damage)
        RPD.glog("defenceProc:"..buff:name()..":"..buff.target:name().." was attacked by "..enemy:name().." for ".. tostring(damage).. " points of raw damage")
        return damage
    end,

    attackProc = function(self, buff, enemy, damage)
        RPD.glog("attackProc:"..buff:name()..":"..buff.target:name().." are attacking "..enemy:name().." for ".. tostring(damage).. " points of raw damage")
        return damage
    end
}
