---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 12/26/19 1:19 AM
---

local util = {}


---@param tbl table
local function table_clone(tbl)
    local ret = {}

    for k,v in pairs(tbl) do
        if type(v)=="table" then
            ret[k] = table_clone(v)
        else
            ret[k] = v
        end
    end
    return ret
end

local function table_foreach_deep(tbl, action, level)
    local ret = {}

    level = level or 0

    for k,v in pairs(tbl) do
        if type(v)=="table" then
            table_foreach_deep(v, action)
        else
            action(k,v, level)
        end
    end
    return ret
end


local function split(str,sep)
    local sep, fields = sep or ":", {}
    local pattern = string.format("([^%s]+)", sep)
    str:gsub(pattern, function(c) fields[#fields+1] = c end)
    return fields
end



util.table_clone        = table_clone
util.table_foreach_deep = table_foreach_deep
util.split = split

--[[ #conflicts with Remixed RPG
getmetatable('').__index = function(str,i)
    if type(i) == 'number' then
        return string.sub(str,i,i)
    else
        return string[i]
    end
end
]]
return util