---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local item = require "scripts.lib.object"


return item.init{
    desc  = function ()
        return {
            image         = 13,
            imageFile     = "items/food.png",
            name          = "FriedFish_Name",
            info          = "FriedFish_Info",
            stackable     = true,
            defaultAction = "Food_ACEat",
            price         = 30
        }
    end,

    image = function(self, object)
        return 1
    end
}