---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"


return object.init{
    desc  = function ()
        return {

        }
    end,

    stepOn = function(self, object, hero)
        return false
    end,

    burn = function(self, object)
        local pos = object:getPos()

        object:level():set(pos, RPD.Terrain.EMBERS)
        object:remove()

        RPD.Effects:burnFX(pos)
        RPD.GameScene:updateMap(pos)
        RPD.Dungeon:observe()
    end,

    losBlocker = function(self, object)
        return true
    end,

    image = function(self, object)
        return 16 * 2 + object:level():objectsKind()
    end
}