---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts.lib.object"


return object.init{
    desc  = function ()
        return {

        }
    end,

    image = function(self, object)
        return 1
    end
}