---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"


return object.init{

    nonPassable = function(self, object)
        return true
    end,

    burn = function(self, object)
        local pos = object:getPos()

        object:level():set(pos, RPD.Terrain.EMBERS)
        object:remove()

        RPD.Effects:burnFX(pos)
        RPD.GameScene:updateMap(pos)
        RPD.Dungeon:observe()
    end,

    losBlocker = function(self, object)
        return true
    end,

    flammable = function(self, object)
        return true
    end,

    textureFile = function(self, object, level)
        if RPD.DungeonTilemap:kind(level) == 'xyz' then
            return "levelObjects/objects.png"
        else
            return level:getTilesTex()
        end
    end,

    image = function(self, object, level)
        if RPD.DungeonTilemap:kind(level) == 'xyz' then
            return 16 * 2 + object:level():objectsKind()
        else
            return RPD.DungeonTilemap:getDecoTileForTerrain(level, object:getPos(), RPD.Terrain.BARRICADE)
        end
    end
}