---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"


return object.init{

    nonPassable = function(self, object, hero)
        return true
    end,

    name = function(self, object, level)
        return level:tileName(RPD.Terrain.STATUE)
    end,

    info = function(self, object, level)
        return level:tileDesc(RPD.Terrain.STATUE)
    end,

    textureFile = function(self, object, level)
        if RPD.DungeonTilemap:kind(level) == 'xyz' then
            return "levelObjects/objects.png"
        else
            return level:getTilesTex()
        end
    end,

    image = function(self, object, level)
        if RPD.DungeonTilemap:kind(level) == 'xyz' then
            return 16 * 8 + level:objectsKind()
        else
            return  RPD.DungeonTilemap:getDecoTileForTerrain(level, object:getPos(), RPD.Terrain.STATUE)
        end
    end
}