---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"


return object.init{
    desc  = function ()
        return {

        }
    end,

    init = function(self, object,level, data)
        local pos = object:getPos()

        RPD.glog("level:".. tostring(level))

        if level:blobAmountAt(RPD.Blobs.WaterOfAwareness, pos) > 0 then
            return
        end

        if level:blobAmountAt(RPD.Blobs.WaterOfHealth, pos) > 0 then
            return
        end

        if level:blobAmountAt(RPD.Blobs.WaterOfTransmutation, pos) > 0 then
            return
        end

        RPD.placeBlob(RPD.Blobs[data],pos,1, level)

    end,

    stepOn = function(self, object, hero)
        return true
    end,

    image = function(self, object)
        return 16 * 5 + object:level():objectsKind()
    end
}