---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 9/25/21 7:41 PM
---

local RPD = require "scripts/lib/commonClasses"

local object = require "scripts/lib/object"


return object.init{
    init = function(self, object, level, data)


        self.data = {water = data}


        local pos = object:getPos()

        if level:blobAmountAt(RPD.Blobs.WaterOfAwareness, pos) > 0 then
            self.data.water = 'WaterOfAwareness'
            return
        end

        if level:blobAmountAt(RPD.Blobs.WaterOfHealth, pos) > 0 then
            self.data.water = 'WaterOfHealth'
            return
        end

        if level:blobAmountAt(RPD.Blobs.WaterOfTransmutation, pos) > 0 then
            self.data.water = 'WaterOfTransmutation'
            return
        end

        if self.data.water then
            RPD.placeBlob(RPD.Blobs[data],pos,1, level)
        end

    end,

    bump = function(self, object, presser)
        RPD.glog("This well full of %s", self.data.water )
        if self.data.water then
            object:level():getBlobByName(self.data.water):affect()
            self.data.water = nil
        end
    end,

    stepOn = function(self, object, hero)
        return true
    end,

    --[[
    interact = function(self, object, hero)
        RPD.glog("This is a well %s", hero:name())
        return false
    end,
]]
    image = function(self, object)

       --RPD.glog(RPD.GameScene.getBaseTilemap():kind())

        return 16 * 5 + object:level():objectsKind()
    end
}