---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 4/1/20 7:42 PM
---

local stats = {}

stats.strForLevel          = { 12, 14, 16, 18 }
stats.chanceForLevel       = { .3, .4, .4, .5 }
stats.blockForLevel        = { 4, 6, 8, 10 }

return stats