name: remixed-dungeon
version: '32.3.alpha.16'
summary: Remixed Dungeon - A classic roguelike dungeon crawler game
description: |
  Remixed Dungeon is a classic roguelike dungeon crawler game with pixel graphics.
  It's a fork of the famous Pixel Dungeon featuring English, Russian and many more localizations.
  This is the desktop version of the game.

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  remixed-dungeon:
    plugin: dump
    source: .
    override-build: |
      set -e
      
      # Create snap directory structure (this ensures directories exist before copying)
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/data
      
      # Build the application using the project's gradlew
      # Java is provided by the build-packages
      ./gradlew -c settings.desktop.gradle :RemixedDungeonDesktop:shadowJar --no-daemon
      
      # Copy the built JAR file - find the correct one based on actual build output
      cp RemixedDungeonDesktop/build/libs/RemixedDungeonDesktop.jar $SNAPCRAFT_PART_INSTALL/bin/remixed-dungeon.jar
      
      # Copy assets and other necessary files
      mkdir -p $SNAPCRAFT_PART_INSTALL/data/mods/Remixed
      cp -r RemixedDungeonDesktop/src/desktop/assets/* $SNAPCRAFT_PART_INSTALL/data/mods/Remixed/
      cp -r RemixedDungeonDesktop/src/desktop/d_assets/* $SNAPCRAFT_PART_INSTALL/data/mods/Remixed/
      cp -r RemixedDungeonDesktop/src/desktop/l10ns/* $SNAPCRAFT_PART_INSTALL/data/mods/Remixed/
      
      # Copy the wrapper script
      cp snap/local/wrapper.sh $SNAPCRAFT_PART_INSTALL/bin/remixed-dungeon-wrapper.sh
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/remixed-dungeon-wrapper.sh
    build-packages:
      - openjdk-17-jdk-headless
      - python3
      - python3-pip
      - python3-lxml
      - wget
      - unzip
      - curl
    stage-packages:
      - openjdk-17-jre-headless
      - libasound2
      - libgtk-3-0
      - libgl1
      - libglu1-mesa
      - libopenal1
      - libflac8
      - libvorbisfile3
      - libudev1
      - libfreetype6
      - libfontconfig1
    prime:
      - bin/
      - data/
      - usr/

apps:
  remixed-dungeon:
    command: bin/remixed-dungeon-wrapper.sh
    plugs:
      - desktop
      - wayland
      - x11
      - opengl
      - audio-playback
      - network
      - home
      - removable-media
    environment:
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_CURRENT_DESKTOP: $XDG_CURRENT_DESKTOP
      XDG_SESSION_DESKTOP: $XDG_SESSION_DESKTOP