---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 2/20/23 12:36 AM
---

local RPD = require "scripts/lib/commonClasses"
local util = require "scripts/lib/util"
local actor = require "scripts/lib/actor"
local sunfish = require "scripts.stuff.chess.sunfish"

local x0 = 4
local y0 = 4

local x_letters = {'a','b','c','d','e','f','g','h'}

local pieces = {}

pieces_set = {
    ['r']='Eye',
    ['R']='Eye',
    ['n']='Succubus',
    ['N']='Succubus',
    ['b']='Shaman',
    ['B']='Shaman',
    ['Q']='Warlock',
    ['q']='Warlock',
    ['K']='King',
    ['k']='King',
    ['p']='Rat',
    ['P']='Rat'
}

chess = nil

local x_letters = {'a','b','c','d','e','f','g','h'}

local function chessCellFromCell(cell)
    local level = RPD.Dungeon.level

    x = level:cellX(cell) - x0
    y = level:cellY(cell) - y0

    if x >= 0 and x < 8 and y >= 0 and y < 8 then
        local chessCell = x_letters[x+1]..tostring(8 - y)
        --RPD.glog("inside of board %d -> %s", cell, chessCell)
        return chessCell
    end

    --RPD.glog("outside of board %d -> %d,%d", cell, x,y)
end

local function cellFromChessCell(chessCell)
    local level = RPD.Dungeon.level

    local x = nil
    for i, letter in ipairs(x_letters) do
        if letter == chessCell:sub(1,1) then
            x = i - 1
            break
        end
    end
    if not x then return nil end -- invalid chess cell
    local y = 8 - tonumber(chessCell:sub(2,2))
    if y < 0 or y > 7 then return nil end -- invalid chess cell

    return level:cell(x + x0, y + y0)
end

local function cellFromChess(x,y)
    local level = RPD.Dungeon.level
    return level:cell(x+x0, y+y0-1)
end

local move_str = ''
local move_cells = {}

return actor.init({
    act = function()
        local level = RPD.Dungeon.level

        local boardData = util.split(chess.board,"\n")
        for i,v in ipairs(boardData) do
            if i >= 3 and i <= 10 then
                local y = i - 2

                local cell = cellFromChess(0,y)

                for ii = 1, 8 do
                    local chessCell = chessCellFromCell(cell)

                    local piece = string.sub(v,ii+1,ii+1)

                    if pieces_set[piece] then
                        if not pieces[chessCell] or pieces[chessCell]:getEntityKind() ~= pieces_set[piece] then
                            local mob = RPD.MobFactory:mobByName(pieces_set[piece])

                            mob:setPos(cell)
                            RPD.setAi(mob,"PASSIVE")
                            level:spawnMob(mob)
                            if piece == piece:upper() then
                                mob:getSprite():hardlight(1.2,1.2,1.2)
                            else
                                mob:getSprite():hardlight(0.8,0.8,0.8)
                            end
                            pieces[chessCell] = mob
                        end
                    end

                    --RPD.glog("%s -> %s", chessCell, piece)
                    cell = cell + 1
                end

                --RPD.glog('\n')

            end

        end
        return true
    end,
    actionTime = function()
        return 1
    end,
    activate = function()
        chess = sunfish.new()
        pieces = {}
    end,

    cellClicked = function(cell)

        chessCell = chessCellFromCell(cell)

        if not chessCell then return false end

        if string.len(move_str) == 0 then
            move_cells[1] = cell
            move_str = chessCell
        else
            move_str = move_str..chessCell
            move_cells[2] = cell
            local mob = RPD.Actor:findChar(move_cells[1])
            RPD.glog(move_str)
            local moveResult = sunfish.move(chess, move_str)
            if moveResult then
                chess = moveResult
                mob:setPos(move_cells[2])
                mob:moveSprite(move_cells[1], move_cells[2])

                chess, ai_move, score = sunfish.ai_move(chess)
                RPD.glog("%s %d", ai_move, score)

                local ai_cells = {string.sub(ai_move,1,2),string.sub(ai_move,3,4)}
                RPD.glog("%s %s", ai_cells[1], ai_cells[2])
                ai_cells = {cellFromChessCell(ai_cells[1]), cellFromChessCell(ai_cells[2])}
                RPD.glog("%s %s", ai_cells[1], ai_cells[2])

                mob = RPD.Actor:findChar(ai_cells[1])
                mob:setPos(ai_cells[2])
                mob:moveSprite(ai_cells[1], ai_cells[2])
            else
                RPD.glog('illegal move')
            end
            move_str = ''
        end

        return false
        end
})