---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 2/19/23 1:06 AM
---

local RPD = require "scripts/lib/commonClasses"
local actor = require "scripts/lib/actor"

return actor.init({
    act = function()
        return true
    end,
    actionTime = function()
        return 10000
    end,
    activate = function()
    end,
    cellClicked = function(cell)
        local level = RPD.Dungeon.level
        local jcell = cell+1
        if level.solid[jcell] then
            RPD.glog("%d solid (%d) -> empty", cell, level.map[jcell])
            level:set(cell, RPD.Terrain.EMPTY)
            RPD.Dungeon:observe()
            return true
        end
        if level.passable[jcell] then
            RPD.glog("%d passable (%d) -> wall", cell, level.map[jcell])
            level:set(cell, RPD.Terrain.WALL)
            RPD.Dungeon:observe()
            return true
        end
        return false
    end
})